# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\workspace\bioparkin\src\simulationworkbench\widgets\databrowser.ui'
#
# Created: Tue Sep 20 10:15:25 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DataBrowser(object):
    def setupUi(self, DataBrowser):
        DataBrowser.setObjectName("DataBrowser")
        DataBrowser.resize(871, 691)
        DataBrowser.setWindowOpacity(1.0)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(DataBrowser)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtGui.QSplitter(DataBrowser)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableView = QtGui.QTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonPlot = QtGui.QPushButton(self.layoutWidget)
        self.buttonPlot.setObjectName("buttonPlot")
        self.horizontalLayout.addWidget(self.buttonPlot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonSaveAs = QtGui.QPushButton(self.layoutWidget)
        self.buttonSaveAs.setObjectName("buttonSaveAs")
        self.verticalLayout.addWidget(self.buttonSaveAs)
        self.toolBox = QtGui.QToolBox(self.layoutWidget)
        self.toolBox.setObjectName("toolBox")
        self.toolbox_Information = QtGui.QWidget()
        self.toolbox_Information.setGeometry(QtCore.QRect(0, 0, 228, 557))
        self.toolbox_Information.setObjectName("toolbox_Information")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.toolbox_Information)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditInfoSpecies = QtGui.QLineEdit(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditInfoSpecies.sizePolicy().hasHeightForWidth())
        self.lineEditInfoSpecies.setSizePolicy(sizePolicy)
        self.lineEditInfoSpecies.setFrame(True)
        self.lineEditInfoSpecies.setReadOnly(True)
        self.lineEditInfoSpecies.setObjectName("lineEditInfoSpecies")
        self.gridLayout.addWidget(self.lineEditInfoSpecies, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.toolbox_Information)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 2)
        self.labelInfoPath = QtGui.QLabel(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfoPath.sizePolicy().hasHeightForWidth())
        self.labelInfoPath.setSizePolicy(sizePolicy)
        self.labelInfoPath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelInfoPath.setObjectName("labelInfoPath")
        self.gridLayout.addWidget(self.labelInfoPath, 10, 0, 1, 1)
        self.lineEditInfoPath = QtGui.QLineEdit(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditInfoPath.sizePolicy().hasHeightForWidth())
        self.lineEditInfoPath.setSizePolicy(sizePolicy)
        self.lineEditInfoPath.setFrame(True)
        self.lineEditInfoPath.setReadOnly(True)
        self.lineEditInfoPath.setObjectName("lineEditInfoPath")
        self.gridLayout.addWidget(self.lineEditInfoPath, 10, 1, 1, 1)
        self.labelInfoFilesize = QtGui.QLabel(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfoFilesize.sizePolicy().hasHeightForWidth())
        self.labelInfoFilesize.setSizePolicy(sizePolicy)
        self.labelInfoFilesize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelInfoFilesize.setObjectName("labelInfoFilesize")
        self.gridLayout.addWidget(self.labelInfoFilesize, 11, 0, 1, 1)
        self.lineEditInfoFilesize = QtGui.QLineEdit(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditInfoFilesize.sizePolicy().hasHeightForWidth())
        self.lineEditInfoFilesize.setSizePolicy(sizePolicy)
        self.lineEditInfoFilesize.setFrame(True)
        self.lineEditInfoFilesize.setReadOnly(True)
        self.lineEditInfoFilesize.setObjectName("lineEditInfoFilesize")
        self.gridLayout.addWidget(self.lineEditInfoFilesize, 11, 1, 1, 1)
        self.labelInfoLastModified = QtGui.QLabel(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfoLastModified.sizePolicy().hasHeightForWidth())
        self.labelInfoLastModified.setSizePolicy(sizePolicy)
        self.labelInfoLastModified.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelInfoLastModified.setObjectName("labelInfoLastModified")
        self.gridLayout.addWidget(self.labelInfoLastModified, 12, 0, 1, 1)
        self.lineEditInfoLastModified = QtGui.QLineEdit(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditInfoLastModified.sizePolicy().hasHeightForWidth())
        self.lineEditInfoLastModified.setSizePolicy(sizePolicy)
        self.lineEditInfoLastModified.setFrame(True)
        self.lineEditInfoLastModified.setReadOnly(True)
        self.lineEditInfoLastModified.setObjectName("lineEditInfoLastModified")
        self.gridLayout.addWidget(self.lineEditInfoLastModified, 12, 1, 1, 1)
        self.labelInfoSpecies = QtGui.QLabel(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfoSpecies.sizePolicy().hasHeightForWidth())
        self.labelInfoSpecies.setSizePolicy(sizePolicy)
        self.labelInfoSpecies.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelInfoSpecies.setObjectName("labelInfoSpecies")
        self.gridLayout.addWidget(self.labelInfoSpecies, 1, 0, 1, 1)
        self.labelInfoFormat = QtGui.QLabel(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfoFormat.sizePolicy().hasHeightForWidth())
        self.labelInfoFormat.setSizePolicy(sizePolicy)
        self.labelInfoFormat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelInfoFormat.setObjectName("labelInfoFormat")
        self.gridLayout.addWidget(self.labelInfoFormat, 9, 0, 1, 1)
        self.lineEditInfoFormat = QtGui.QLineEdit(self.toolbox_Information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditInfoFormat.sizePolicy().hasHeightForWidth())
        self.lineEditInfoFormat.setSizePolicy(sizePolicy)
        self.lineEditInfoFormat.setFrame(True)
        self.lineEditInfoFormat.setReadOnly(True)
        self.lineEditInfoFormat.setObjectName("lineEditInfoFormat")
        self.gridLayout.addWidget(self.lineEditInfoFormat, 9, 1, 1, 1)
        self.lineEditInfoDataType = QtGui.QLineEdit(self.toolbox_Information)
        self.lineEditInfoDataType.setReadOnly(True)
        self.lineEditInfoDataType.setObjectName("lineEditInfoDataType")
        self.gridLayout.addWidget(self.lineEditInfoDataType, 2, 1, 1, 1)
        self.labelInfoDataType = QtGui.QLabel(self.toolbox_Information)
        self.labelInfoDataType.setObjectName("labelInfoDataType")
        self.gridLayout.addWidget(self.labelInfoDataType, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.toolbox_Information)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.toolbox_Information)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 8, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 418, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.toolBox.addItem(self.toolbox_Information, "")
        self.toolbox_advancedFeatures = QtGui.QWidget()
        self.toolbox_advancedFeatures.setGeometry(QtCore.QRect(0, 0, 228, 557))
        self.toolbox_advancedFeatures.setObjectName("toolbox_advancedFeatures")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.toolbox_advancedFeatures)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelPerturb = QtGui.QLabel(self.toolbox_advancedFeatures)
        self.labelPerturb.setObjectName("labelPerturb")
        self.horizontalLayout_3.addWidget(self.labelPerturb)
        self.spinBoxPerturb = QtGui.QDoubleSpinBox(self.toolbox_advancedFeatures)
        self.spinBoxPerturb.setDecimals(1)
        self.spinBoxPerturb.setSingleStep(0.5)
        self.spinBoxPerturb.setProperty("value", 5.0)
        self.spinBoxPerturb.setObjectName("spinBoxPerturb")
        self.horizontalLayout_3.addWidget(self.spinBoxPerturb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.buttonPerturb = QtGui.QPushButton(self.toolbox_advancedFeatures)
        self.buttonPerturb.setObjectName("buttonPerturb")
        self.verticalLayout_2.addWidget(self.buttonPerturb)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 498, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.toolBox.addItem(self.toolbox_advancedFeatures, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.actionPlot = QtGui.QAction(DataBrowser)
        self.actionPlot.setObjectName("actionPlot")

        self.retranslateUi(DataBrowser)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonPlot, QtCore.SIGNAL("clicked()"), self.actionPlot.trigger)
        QtCore.QMetaObject.connectSlotsByName(DataBrowser)

    def retranslateUi(self, DataBrowser):
        DataBrowser.setWindowTitle(QtGui.QApplication.translate("DataBrowser", "DataBrowser", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlot.setText(QtGui.QApplication.translate("DataBrowser", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveAs.setText(QtGui.QApplication.translate("DataBrowser", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfoPath.setText(QtGui.QApplication.translate("DataBrowser", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfoFilesize.setText(QtGui.QApplication.translate("DataBrowser", "Filesize:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfoLastModified.setText(QtGui.QApplication.translate("DataBrowser", "Last Modified:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfoSpecies.setText(QtGui.QApplication.translate("DataBrowser", "# Species:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfoFormat.setText(QtGui.QApplication.translate("DataBrowser", "Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfoDataType.setText(QtGui.QApplication.translate("DataBrowser", "Data Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DataBrowser", "<b>Data</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DataBrowser", "<b>File</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolbox_Information), QtGui.QApplication.translate("DataBrowser", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPerturb.setText(QtGui.QApplication.translate("DataBrowser", "Perturbation Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxPerturb.setSuffix(QtGui.QApplication.translate("DataBrowser", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPerturb.setText(QtGui.QApplication.translate("DataBrowser", "Perturb Data", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolbox_advancedFeatures), QtGui.QApplication.translate("DataBrowser", "Advanced Features", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot.setText(QtGui.QApplication.translate("DataBrowser", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot.setToolTip(QtGui.QApplication.translate("DataBrowser", "Plot this data set.", None, QtGui.QApplication.UnicodeUTF8))

