# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\workspace\BioPARKIN\src\simulationworkbench\widgets\timepointchooser.ui'
#
# Created: Thu Sep 29 13:30:31 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TimepointChooser(object):
    def setupUi(self, TimepointChooser):
        TimepointChooser.setObjectName("TimepointChooser")
        TimepointChooser.setWindowModality(QtCore.Qt.ApplicationModal)
        TimepointChooser.setEnabled(True)
        TimepointChooser.resize(849, 452)
        TimepointChooser.setWhatsThis("")
        TimepointChooser.setSizeGripEnabled(True)
        self.horizontalLayout_6 = QtGui.QHBoxLayout(TimepointChooser)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_FromData = QtGui.QGroupBox(TimepointChooser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_FromData.sizePolicy().hasHeightForWidth())
        self.groupBox_FromData.setSizePolicy(sizePolicy)
        self.groupBox_FromData.setObjectName("groupBox_FromData")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_FromData)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_FromData = QtGui.QPushButton(self.groupBox_FromData)
        self.button_FromData.setObjectName("button_FromData")
        self.horizontalLayout.addWidget(self.button_FromData)
        self.horizontalLayout_3.addWidget(self.groupBox_FromData)
        self.label_5 = QtGui.QLabel(TimepointChooser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.groupBox_Calculate = QtGui.QGroupBox(TimepointChooser)
        self.groupBox_Calculate.setObjectName("groupBox_Calculate")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_Calculate)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_StartTime = QtGui.QLabel(self.groupBox_Calculate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_StartTime.sizePolicy().hasHeightForWidth())
        self.label_StartTime.setSizePolicy(sizePolicy)
        self.label_StartTime.setObjectName("label_StartTime")
        self.gridLayout.addWidget(self.label_StartTime, 0, 0, 1, 1)
        self.lineEdit_StartTime = QtGui.QLineEdit(self.groupBox_Calculate)
        self.lineEdit_StartTime.setObjectName("lineEdit_StartTime")
        self.gridLayout.addWidget(self.lineEdit_StartTime, 0, 1, 1, 1)
        self.label_EndTime = QtGui.QLabel(self.groupBox_Calculate)
        self.label_EndTime.setObjectName("label_EndTime")
        self.gridLayout.addWidget(self.label_EndTime, 1, 0, 1, 1)
        self.lineEdit_EndTime = QtGui.QLineEdit(self.groupBox_Calculate)
        self.lineEdit_EndTime.setObjectName("lineEdit_EndTime")
        self.gridLayout.addWidget(self.lineEdit_EndTime, 1, 1, 1, 1)
        self.label_NumIntervals = QtGui.QLabel(self.groupBox_Calculate)
        self.label_NumIntervals.setObjectName("label_NumIntervals")
        self.gridLayout.addWidget(self.label_NumIntervals, 2, 0, 1, 1)
        self.lineEdit_NumIntervals = QtGui.QLineEdit(self.groupBox_Calculate)
        self.lineEdit_NumIntervals.setObjectName("lineEdit_NumIntervals")
        self.gridLayout.addWidget(self.lineEdit_NumIntervals, 2, 1, 1, 1)
        self.label_IntervalSize = QtGui.QLabel(self.groupBox_Calculate)
        self.label_IntervalSize.setObjectName("label_IntervalSize")
        self.gridLayout.addWidget(self.label_IntervalSize, 3, 0, 1, 1)
        self.lineEdit_IntervalSize = QtGui.QLineEdit(self.groupBox_Calculate)
        self.lineEdit_IntervalSize.setObjectName("lineEdit_IntervalSize")
        self.gridLayout.addWidget(self.lineEdit_IntervalSize, 3, 1, 1, 1)
        self.button_Calculate = QtGui.QPushButton(self.groupBox_Calculate)
        self.button_Calculate.setObjectName("button_Calculate")
        self.gridLayout.addWidget(self.button_Calculate, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_3.addWidget(self.groupBox_Calculate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_Timepoints = QtGui.QGroupBox(TimepointChooser)
        self.groupBox_Timepoints.setObjectName("groupBox_Timepoints")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_Timepoints)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.plainTextEdit_Timepoints = QtGui.QPlainTextEdit(self.groupBox_Timepoints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_Timepoints.setFont(font)
        self.plainTextEdit_Timepoints.setProperty("cursor", QtCore.Qt.IBeamCursor)
        self.plainTextEdit_Timepoints.setObjectName("plainTextEdit_Timepoints")
        self.horizontalLayout_5.addWidget(self.plainTextEdit_Timepoints)
        self.verticalLayout.addWidget(self.groupBox_Timepoints)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(368, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.labelTimepointsInvalid = QtGui.QLabel(TimepointChooser)
        self.labelTimepointsInvalid.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.labelTimepointsInvalid.setFont(font)
        self.labelTimepointsInvalid.setScaledContents(False)
        self.labelTimepointsInvalid.setObjectName("labelTimepointsInvalid")
        self.horizontalLayout_4.addWidget(self.labelTimepointsInvalid)
        self.buttonBox = QtGui.QDialogButtonBox(TimepointChooser)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Abort|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout)

        self.retranslateUi(TimepointChooser)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), TimepointChooser.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), TimepointChooser.reject)
        QtCore.QMetaObject.connectSlotsByName(TimepointChooser)

    def retranslateUi(self, TimepointChooser):
        TimepointChooser.setWindowTitle(QtGui.QApplication.translate("TimepointChooser", "Choose Timepoints", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_FromData.setTitle(QtGui.QApplication.translate("TimepointChooser", "Get From Data", None, QtGui.QApplication.UnicodeUTF8))
        self.button_FromData.setText(QtGui.QApplication.translate("TimepointChooser", "Get Timepoints from Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TimepointChooser", "or", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Calculate.setTitle(QtGui.QApplication.translate("TimepointChooser", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_StartTime.setText(QtGui.QApplication.translate("TimepointChooser", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_EndTime.setText(QtGui.QApplication.translate("TimepointChooser", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NumIntervals.setText(QtGui.QApplication.translate("TimepointChooser", "# Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.label_IntervalSize.setText(QtGui.QApplication.translate("TimepointChooser", "Interval Size", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Calculate.setText(QtGui.QApplication.translate("TimepointChooser", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Timepoints.setTitle(QtGui.QApplication.translate("TimepointChooser", "Timepoints (space-separated)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTimepointsInvalid.setText(QtGui.QApplication.translate("TimepointChooser", "The list of time points is invalid! (It may only contain digits, e.g. \"12.5\", delimited by white space.)", None, QtGui.QApplication.UnicodeUTF8))

