# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\workspace\bioparkin\src\simulationworkbench\widgets\tablewidget_v1.ui'
#
# Created: Tue Sep 27 13:50:40 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TableWidget(object):
    def setupUi(self, TableWidget):
        TableWidget.setObjectName("TableWidget")
        TableWidget.resize(793, 621)
        self.horizontalLayout = QtGui.QHBoxLayout(TableWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtGui.QSplitter(TableWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabWidgetPage1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dataSourceTableView = QtGui.QTableView(self.tabWidgetPage1)
        self.dataSourceTableView.setObjectName("dataSourceTableView")
        self.verticalLayout_3.addWidget(self.dataSourceTableView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonSelectAll = QtGui.QPushButton(self.tabWidgetPage1)
        self.buttonSelectAll.setObjectName("buttonSelectAll")
        self.horizontalLayout_2.addWidget(self.buttonSelectAll)
        self.buttonDeselectAll = QtGui.QPushButton(self.tabWidgetPage1)
        self.buttonDeselectAll.setObjectName("buttonDeselectAll")
        self.horizontalLayout_2.addWidget(self.buttonDeselectAll)
        self.buttonInvertSelection = QtGui.QPushButton(self.tabWidgetPage1)
        self.buttonInvertSelection.setObjectName("buttonInvertSelection")
        self.horizontalLayout_2.addWidget(self.buttonInvertSelection)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabWidgetPage2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxShowUnits = QtGui.QCheckBox(self.tabWidgetPage2)
        self.checkBoxShowUnits.setChecked(True)
        self.checkBoxShowUnits.setObjectName("checkBoxShowUnits")
        self.verticalLayout.addWidget(self.checkBoxShowUnits)
        self.checkBoxOrientation = QtGui.QCheckBox(self.tabWidgetPage2)
        self.checkBoxOrientation.setObjectName("checkBoxOrientation")
        self.verticalLayout.addWidget(self.checkBoxOrientation)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonSaveTable = QtGui.QPushButton(self.tabWidgetPage2)
        self.buttonSaveTable.setObjectName("buttonSaveTable")
        self.verticalLayout_2.addWidget(self.buttonSaveTable)
        spacerItem1 = QtGui.QSpacerItem(20, 429, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.buttonSetExperimentalData = QtGui.QPushButton(self.tabWidgetPage2)
        self.buttonSetExperimentalData.setFlat(False)
        self.buttonSetExperimentalData.setObjectName("buttonSetExperimentalData")
        self.verticalLayout_2.addWidget(self.buttonSetExperimentalData)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tableWrapper = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWrapper.sizePolicy().hasHeightForWidth())
        self.tableWrapper.setSizePolicy(sizePolicy)
        self.tableWrapper.setObjectName("tableWrapper")
        self.horizontalLayout.addWidget(self.splitter)
        self.actionSave = QtGui.QAction(TableWidget)
        self.actionSave.setObjectName("actionSave")
        self.actionAddToExperimentalData = QtGui.QAction(TableWidget)
        self.actionAddToExperimentalData.setObjectName("actionAddToExperimentalData")
        self.actionSelectAll = QtGui.QAction(TableWidget)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.actionDeselectAll = QtGui.QAction(TableWidget)
        self.actionDeselectAll.setObjectName("actionDeselectAll")
        self.actionInvertSelection = QtGui.QAction(TableWidget)
        self.actionInvertSelection.setObjectName("actionInvertSelection")

        self.retranslateUi(TableWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonSetExperimentalData, QtCore.SIGNAL("clicked()"), self.actionAddToExperimentalData.trigger)
        QtCore.QObject.connect(self.buttonSelectAll, QtCore.SIGNAL("clicked()"), self.actionSelectAll.trigger)
        QtCore.QObject.connect(self.buttonDeselectAll, QtCore.SIGNAL("clicked()"), self.actionDeselectAll.trigger)
        QtCore.QObject.connect(self.buttonInvertSelection, QtCore.SIGNAL("clicked()"), self.actionInvertSelection.trigger)
        QtCore.QObject.connect(self.buttonSaveTable, QtCore.SIGNAL("clicked()"), self.actionSave.trigger)
        QtCore.QMetaObject.connectSlotsByName(TableWidget)

    def retranslateUi(self, TableWidget):
        TableWidget.setWindowTitle(QtGui.QApplication.translate("TableWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAll.setText(QtGui.QApplication.translate("TableWidget", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAll.setText(QtGui.QApplication.translate("TableWidget", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelection.setText(QtGui.QApplication.translate("TableWidget", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("TableWidget", "Data Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowUnits.setText(QtGui.QApplication.translate("TableWidget", "Show Units in Table Headers", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOrientation.setText(QtGui.QApplication.translate("TableWidget", "Switch rows vs. columns", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveTable.setText(QtGui.QApplication.translate("TableWidget", "Save Data...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSetExperimentalData.setText(QtGui.QApplication.translate("TableWidget", "Add Data to Data Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QtGui.QApplication.translate("TableWidget", "Settings && Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("TableWidget", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("TableWidget", "Save the current plot.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddToExperimentalData.setText(QtGui.QApplication.translate("TableWidget", "Add Data to Experimental Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddToExperimentalData.setToolTip(QtGui.QApplication.translate("TableWidget", "Adds the currently displayed data and adds it to the experimental data. This is usually only useful if you want to want to use simulation results (which can then be perturbed) as input for other tools like parameter value estimation.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setText(QtGui.QApplication.translate("TableWidget", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setToolTip(QtGui.QApplication.translate("TableWidget", "Select All Data Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselectAll.setText(QtGui.QApplication.translate("TableWidget", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselectAll.setToolTip(QtGui.QApplication.translate("TableWidget", "Deselect All Data Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvertSelection.setText(QtGui.QApplication.translate("TableWidget", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvertSelection.setToolTip(QtGui.QApplication.translate("TableWidget", "Invert the Current Selection of Data Sources", None, QtGui.QApplication.UnicodeUTF8))

