# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\workspace\bioparkin\src\simulationworkbench\simulationworkbench_v3.ui'
#
# Created: Tue Sep 20 10:15:24 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SimulationWorkbench(object):
    def setupUi(self, SimulationWorkbench):
        SimulationWorkbench.setObjectName("SimulationWorkbench")
        SimulationWorkbench.resize(876, 620)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SimulationWorkbench.sizePolicy().hasHeightForWidth())
        SimulationWorkbench.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(SimulationWorkbench)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.actionTabWidget = QtGui.QTabWidget(SimulationWorkbench)
        self.actionTabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.actionTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.actionTabWidget.setObjectName("actionTabWidget")
        self.tabSpecies = QtGui.QWidget()
        self.tabSpecies.setObjectName("tabSpecies")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tabSpecies)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.speciesTableView = QtGui.QTableView(self.tabSpecies)
        self.speciesTableView.setObjectName("speciesTableView")
        self.verticalLayout_5.addWidget(self.speciesTableView)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.simulateButtonSpecies = QtGui.QPushButton(self.tabSpecies)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButtonSpecies.sizePolicy().hasHeightForWidth())
        self.simulateButtonSpecies.setSizePolicy(sizePolicy)
        self.simulateButtonSpecies.setObjectName("simulateButtonSpecies")
        self.horizontalLayout_5.addWidget(self.simulateButtonSpecies)
        self.resetButtonSpecies = QtGui.QPushButton(self.tabSpecies)
        self.resetButtonSpecies.setObjectName("resetButtonSpecies")
        self.horizontalLayout_5.addWidget(self.resetButtonSpecies)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.actionTabWidget.addTab(self.tabSpecies, "")
        self.tabParameters = QtGui.QWidget()
        self.tabParameters.setObjectName("tabParameters")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tabParameters)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.parametersTableView = QtGui.QTableView(self.tabParameters)
        self.parametersTableView.setObjectName("parametersTableView")
        self.verticalLayout.addWidget(self.parametersTableView)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.simulateButtonParams = QtGui.QPushButton(self.tabParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButtonParams.sizePolicy().hasHeightForWidth())
        self.simulateButtonParams.setSizePolicy(sizePolicy)
        self.simulateButtonParams.setObjectName("simulateButtonParams")
        self.horizontalLayout_7.addWidget(self.simulateButtonParams)
        self.resetButtonParams = QtGui.QPushButton(self.tabParameters)
        self.resetButtonParams.setObjectName("resetButtonParams")
        self.horizontalLayout_7.addWidget(self.resetButtonParams)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.actionTabWidget.addTab(self.tabParameters, "")
        self.tabParameterSets = QtGui.QWidget()
        self.tabParameterSets.setObjectName("tabParameterSets")
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.tabParameterSets)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.parameterSetsTableView = QtGui.QTableView(self.tabParameterSets)
        self.parameterSetsTableView.setObjectName("parameterSetsTableView")
        self.verticalLayout_13.addWidget(self.parameterSetsTableView)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.buttonParamSetNew = QtGui.QPushButton(self.tabParameterSets)
        self.buttonParamSetNew.setObjectName("buttonParamSetNew")
        self.horizontalLayout_17.addWidget(self.buttonParamSetNew)
        self.buttonParamSetDuplicate = QtGui.QPushButton(self.tabParameterSets)
        self.buttonParamSetDuplicate.setObjectName("buttonParamSetDuplicate")
        self.horizontalLayout_17.addWidget(self.buttonParamSetDuplicate)
        self.buttonParamSetRemove = QtGui.QPushButton(self.tabParameterSets)
        self.buttonParamSetRemove.setObjectName("buttonParamSetRemove")
        self.horizontalLayout_17.addWidget(self.buttonParamSetRemove)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_13)
        self.actionTabWidget.addTab(self.tabParameterSets, "")
        self.tabSensitivity = QtGui.QWidget()
        self.tabSensitivity.setObjectName("tabSensitivity")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.tabSensitivity)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sensitivityTableView = QtGui.QTableView(self.tabSensitivity)
        self.sensitivityTableView.setObjectName("sensitivityTableView")
        self.verticalLayout_2.addWidget(self.sensitivityTableView)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.buttonSelectAllSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonSelectAllSensitivity.setObjectName("buttonSelectAllSensitivity")
        self.horizontalLayout_13.addWidget(self.buttonSelectAllSensitivity)
        self.buttonDeselectAllSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonDeselectAllSensitivity.setObjectName("buttonDeselectAllSensitivity")
        self.horizontalLayout_13.addWidget(self.buttonDeselectAllSensitivity)
        self.buttonInvertSelectionSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonInvertSelectionSensitivity.setObjectName("buttonInvertSelectionSensitivity")
        self.horizontalLayout_13.addWidget(self.buttonInvertSelectionSensitivity)
        self.computeSensitivitiesButton = QtGui.QPushButton(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.computeSensitivitiesButton.sizePolicy().hasHeightForWidth())
        self.computeSensitivitiesButton.setSizePolicy(sizePolicy)
        self.computeSensitivitiesButton.setObjectName("computeSensitivitiesButton")
        self.horizontalLayout_13.addWidget(self.computeSensitivitiesButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.labelSensitivitiesText = QtGui.QLabel(self.tabSensitivity)
        self.labelSensitivitiesText.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSensitivitiesText.setObjectName("labelSensitivitiesText")
        self.verticalLayout_2.addWidget(self.labelSensitivitiesText)
        self.horizontalLayout_14.addLayout(self.verticalLayout_2)
        self.actionTabWidget.addTab(self.tabSensitivity, "")
        self.tabFit = QtGui.QWidget()
        self.tabFit.setObjectName("tabFit")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.tabFit)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.estimateParamsTableView = QtGui.QTableView(self.tabFit)
        self.estimateParamsTableView.setObjectName("estimateParamsTableView")
        self.verticalLayout_3.addWidget(self.estimateParamsTableView)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.buttonSelectAllParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonSelectAllParamEst.setObjectName("buttonSelectAllParamEst")
        self.horizontalLayout_15.addWidget(self.buttonSelectAllParamEst)
        self.buttonDeselectAllParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonDeselectAllParamEst.setObjectName("buttonDeselectAllParamEst")
        self.horizontalLayout_15.addWidget(self.buttonDeselectAllParamEst)
        self.buttonInvertSelectionParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonInvertSelectionParamEst.setObjectName("buttonInvertSelectionParamEst")
        self.horizontalLayout_15.addWidget(self.buttonInvertSelectionParamEst)
        self.estimateParamsButton = QtGui.QPushButton(self.tabFit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estimateParamsButton.sizePolicy().hasHeightForWidth())
        self.estimateParamsButton.setSizePolicy(sizePolicy)
        self.estimateParamsButton.setObjectName("estimateParamsButton")
        self.horizontalLayout_15.addWidget(self.estimateParamsButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16.addLayout(self.verticalLayout_3)
        self.actionTabWidget.addTab(self.tabFit, "")
        self.tabExperimentalData = QtGui.QWidget()
        self.tabExperimentalData.setObjectName("tabExperimentalData")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tabExperimentalData)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.experimentalDataToolBox = QtGui.QToolBox(self.tabExperimentalData)
        self.experimentalDataToolBox.setObjectName("experimentalDataToolBox")
        self.pageMainFeatures = QtGui.QWidget()
        self.pageMainFeatures.setGeometry(QtCore.QRect(0, 0, 814, 524))
        self.pageMainFeatures.setObjectName("pageMainFeatures")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.pageMainFeatures)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEditExpData = QtGui.QLineEdit(self.pageMainFeatures)
        self.lineEditExpData.setObjectName("lineEditExpData")
        self.horizontalLayout_9.addWidget(self.lineEditExpData)
        self.buttonBrowseExpData = QtGui.QPushButton(self.pageMainFeatures)
        self.buttonBrowseExpData.setObjectName("buttonBrowseExpData")
        self.horizontalLayout_9.addWidget(self.buttonBrowseExpData)
        self.buttonImportExpData = QtGui.QPushButton(self.pageMainFeatures)
        self.buttonImportExpData.setObjectName("buttonImportExpData")
        self.horizontalLayout_9.addWidget(self.buttonImportExpData)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.tableWidgetExpData = QtGui.QTableWidget(self.pageMainFeatures)
        self.tableWidgetExpData.setObjectName("tableWidgetExpData")
        self.tableWidgetExpData.setColumnCount(0)
        self.tableWidgetExpData.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tableWidgetExpData)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonPlotExperimentalData = QtGui.QPushButton(self.pageMainFeatures)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlotExperimentalData.sizePolicy().hasHeightForWidth())
        self.buttonPlotExperimentalData.setSizePolicy(sizePolicy)
        self.buttonPlotExperimentalData.setObjectName("buttonPlotExperimentalData")
        self.horizontalLayout_4.addWidget(self.buttonPlotExperimentalData)
        spacerItem1 = QtGui.QSpacerItem(498, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.buttonExpDataRemoveSelected = QtGui.QPushButton(self.pageMainFeatures)
        self.buttonExpDataRemoveSelected.setObjectName("buttonExpDataRemoveSelected")
        self.horizontalLayout_4.addWidget(self.buttonExpDataRemoveSelected)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.experimentalDataToolBox.addItem(self.pageMainFeatures, "")
        self.pageAdvancedFeatures = QtGui.QWidget()
        self.pageAdvancedFeatures.setGeometry(QtCore.QRect(0, 0, 335, 51))
        self.pageAdvancedFeatures.setObjectName("pageAdvancedFeatures")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.pageAdvancedFeatures)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.perturbExpDataLabel = QtGui.QLabel(self.pageAdvancedFeatures)
        self.perturbExpDataLabel.setObjectName("perturbExpDataLabel")
        self.horizontalLayout_11.addWidget(self.perturbExpDataLabel)
        self.perturbExpDataDoubleSpinBox = QtGui.QDoubleSpinBox(self.pageAdvancedFeatures)
        self.perturbExpDataDoubleSpinBox.setDecimals(1)
        self.perturbExpDataDoubleSpinBox.setMaximum(100.0)
        self.perturbExpDataDoubleSpinBox.setSingleStep(0.5)
        self.perturbExpDataDoubleSpinBox.setProperty("value", 5.0)
        self.perturbExpDataDoubleSpinBox.setObjectName("perturbExpDataDoubleSpinBox")
        self.horizontalLayout_11.addWidget(self.perturbExpDataDoubleSpinBox)
        self.perturbExpDataPushButton = QtGui.QPushButton(self.pageAdvancedFeatures)
        self.perturbExpDataPushButton.setObjectName("perturbExpDataPushButton")
        self.horizontalLayout_11.addWidget(self.perturbExpDataPushButton)
        spacerItem2 = QtGui.QSpacerItem(368, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtGui.QSpacerItem(20, 458, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.experimentalDataToolBox.addItem(self.pageAdvancedFeatures, "")
        self.horizontalLayout_10.addWidget(self.experimentalDataToolBox)
        self.actionTabWidget.addTab(self.tabExperimentalData, "")
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tabSettings)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.tabSettings)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelComputationBackend = QtGui.QLabel(self.groupBox)
        self.labelComputationBackend.setObjectName("labelComputationBackend")
        self.horizontalLayout_2.addWidget(self.labelComputationBackend)
        self.comboBoxBackendSelect = QtGui.QComboBox(self.groupBox)
        self.comboBoxBackendSelect.setObjectName("comboBoxBackendSelect")
        self.comboBoxBackendSelect.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxBackendSelect)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.autoRefreshCheckBox = QtGui.QCheckBox(self.groupBox)
        self.autoRefreshCheckBox.setObjectName("autoRefreshCheckBox")
        self.verticalLayout_7.addWidget(self.autoRefreshCheckBox)
        self.checkBoxPlotExpData = QtGui.QCheckBox(self.groupBox)
        self.checkBoxPlotExpData.setObjectName("checkBoxPlotExpData")
        self.verticalLayout_7.addWidget(self.checkBoxPlotExpData)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBoxTimes = QtGui.QGroupBox(self.tabSettings)
        self.groupBoxTimes.setObjectName("groupBoxTimes")
        self.gridLayout = QtGui.QGridLayout(self.groupBoxTimes)
        self.gridLayout.setObjectName("gridLayout")
        self.labelStartTime = QtGui.QLabel(self.groupBoxTimes)
        self.labelStartTime.setObjectName("labelStartTime")
        self.gridLayout.addWidget(self.labelStartTime, 1, 0, 1, 1)
        self.lineEditStartTime = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditStartTime.setText("")
        self.lineEditStartTime.setObjectName("lineEditStartTime")
        self.gridLayout.addWidget(self.lineEditStartTime, 1, 1, 1, 1)
        self.labelEndTime = QtGui.QLabel(self.groupBoxTimes)
        self.labelEndTime.setObjectName("labelEndTime")
        self.gridLayout.addWidget(self.labelEndTime, 2, 0, 1, 1)
        self.lineEditEndTime = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditEndTime.setText("")
        self.lineEditEndTime.setObjectName("lineEditEndTime")
        self.gridLayout.addWidget(self.lineEditEndTime, 2, 1, 1, 1)
        self.labelTimeUnit = QtGui.QLabel(self.groupBoxTimes)
        self.labelTimeUnit.setObjectName("labelTimeUnit")
        self.gridLayout.addWidget(self.labelTimeUnit, 5, 0, 1, 1)
        self.lineEditTimeUnit = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditTimeUnit.setText("")
        self.lineEditTimeUnit.setObjectName("lineEditTimeUnit")
        self.gridLayout.addWidget(self.lineEditTimeUnit, 5, 1, 1, 1)
        self.labelNumIntervals = QtGui.QLabel(self.groupBoxTimes)
        self.labelNumIntervals.setObjectName("labelNumIntervals")
        self.gridLayout.addWidget(self.labelNumIntervals, 3, 0, 1, 1)
        self.lineEditNumIntervals = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditNumIntervals.setText("")
        self.lineEditNumIntervals.setObjectName("lineEditNumIntervals")
        self.gridLayout.addWidget(self.lineEditNumIntervals, 3, 1, 1, 1)
        self.checkBoxUseMeasuredTimepoints = QtGui.QCheckBox(self.groupBoxTimes)
        self.checkBoxUseMeasuredTimepoints.setObjectName("checkBoxUseMeasuredTimepoints")
        self.gridLayout.addWidget(self.checkBoxUseMeasuredTimepoints, 0, 0, 1, 1)
        self.labelIntervalSize = QtGui.QLabel(self.groupBoxTimes)
        self.labelIntervalSize.setObjectName("labelIntervalSize")
        self.gridLayout.addWidget(self.labelIntervalSize, 4, 0, 1, 1)
        self.lineEditIntervalSize = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditIntervalSize.setObjectName("lineEditIntervalSize")
        self.gridLayout.addWidget(self.lineEditIntervalSize, 4, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBoxTimes)
        self.groupBoxTolerances = QtGui.QGroupBox(self.tabSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTolerances.sizePolicy().hasHeightForWidth())
        self.groupBoxTolerances.setSizePolicy(sizePolicy)
        self.groupBoxTolerances.setFlat(False)
        self.groupBoxTolerances.setCheckable(False)
        self.groupBoxTolerances.setObjectName("groupBoxTolerances")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxTolerances)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelRTOL = QtGui.QLabel(self.groupBoxTolerances)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRTOL.sizePolicy().hasHeightForWidth())
        self.labelRTOL.setSizePolicy(sizePolicy)
        self.labelRTOL.setObjectName("labelRTOL")
        self.gridLayout_2.addWidget(self.labelRTOL, 0, 0, 1, 1)
        self.lineEditRTOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditRTOL.setText("")
        self.lineEditRTOL.setObjectName("lineEditRTOL")
        self.gridLayout_2.addWidget(self.lineEditRTOL, 0, 1, 1, 1)
        self.labelATOL = QtGui.QLabel(self.groupBoxTolerances)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelATOL.sizePolicy().hasHeightForWidth())
        self.labelATOL.setSizePolicy(sizePolicy)
        self.labelATOL.setObjectName("labelATOL")
        self.gridLayout_2.addWidget(self.labelATOL, 1, 0, 1, 1)
        self.lineEditATOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditATOL.setText("")
        self.lineEditATOL.setObjectName("lineEditATOL")
        self.gridLayout_2.addWidget(self.lineEditATOL, 1, 1, 1, 1)
        self.labelXTOL = QtGui.QLabel(self.groupBoxTolerances)
        self.labelXTOL.setObjectName("labelXTOL")
        self.gridLayout_2.addWidget(self.labelXTOL, 2, 0, 1, 1)
        self.lineEditXTOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditXTOL.setObjectName("lineEditXTOL")
        self.gridLayout_2.addWidget(self.lineEditXTOL, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBoxTolerances)
        spacerItem5 = QtGui.QSpacerItem(20, 238, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.simulateButtonSettings = QtGui.QPushButton(self.tabSettings)
        self.simulateButtonSettings.setObjectName("simulateButtonSettings")
        self.verticalLayout_4.addWidget(self.simulateButtonSettings)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.actionTabWidget.addTab(self.tabSettings, "")
        self.horizontalLayout.addWidget(self.actionTabWidget)
        self.actionSimulate = QtGui.QAction(SimulationWorkbench)
        self.actionSimulate.setObjectName("actionSimulate")
        self.actionReset = QtGui.QAction(SimulationWorkbench)
        self.actionReset.setObjectName("actionReset")
        self.actionImport = QtGui.QAction(SimulationWorkbench)
        self.actionImport.setObjectName("actionImport")
        self.actionSaveData = QtGui.QAction(SimulationWorkbench)
        self.actionSaveData.setObjectName("actionSaveData")
        self.actionSavePlot = QtGui.QAction(SimulationWorkbench)
        self.actionSavePlot.setObjectName("actionSavePlot")
        self.actionAutoRefresh = QtGui.QAction(SimulationWorkbench)
        self.actionAutoRefresh.setCheckable(True)
        self.actionAutoRefresh.setObjectName("actionAutoRefresh")
        self.actionComputeSensitivities = QtGui.QAction(SimulationWorkbench)
        self.actionComputeSensitivities.setObjectName("actionComputeSensitivities")
        self.actionResetSpecies = QtGui.QAction(SimulationWorkbench)
        self.actionResetSpecies.setObjectName("actionResetSpecies")
        self.actionResetParameters = QtGui.QAction(SimulationWorkbench)
        self.actionResetParameters.setObjectName("actionResetParameters")
        self.actionEstimateParameterValues = QtGui.QAction(SimulationWorkbench)
        self.actionEstimateParameterValues.setObjectName("actionEstimateParameterValues")
        self.actionPerturbExperimentalData = QtGui.QAction(SimulationWorkbench)
        self.actionPerturbExperimentalData.setObjectName("actionPerturbExperimentalData")
        self.actionSelectAllParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionSelectAllParametersForSensitivity.setObjectName("actionSelectAllParametersForSensitivity")
        self.actionDeselectAllParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionDeselectAllParametersForSensitivity.setObjectName("actionDeselectAllParametersForSensitivity")
        self.actionInvertSelectionOfParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionInvertSelectionOfParametersForSensitivity.setObjectName("actionInvertSelectionOfParametersForSensitivity")
        self.actionSelect_All_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionSelect_All_Parameters_for_Estimation.setObjectName("actionSelect_All_Parameters_for_Estimation")
        self.actionDeselect_All_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionDeselect_All_Parameters_for_Estimation.setObjectName("actionDeselect_All_Parameters_for_Estimation")
        self.actionInvert_Selection_of_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionInvert_Selection_of_Parameters_for_Estimation.setObjectName("actionInvert_Selection_of_Parameters_for_Estimation")
        self.actionNew_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionNew_Parameter_Set.setObjectName("actionNew_Parameter_Set")
        self.actionDuplicate_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionDuplicate_Parameter_Set.setObjectName("actionDuplicate_Parameter_Set")
        self.actionRemove_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionRemove_Parameter_Set.setObjectName("actionRemove_Parameter_Set")

        self.retranslateUi(SimulationWorkbench)
        self.actionTabWidget.setCurrentIndex(0)
        self.experimentalDataToolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.simulateButtonSpecies, QtCore.SIGNAL("clicked()"), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.resetButtonSpecies, QtCore.SIGNAL("clicked()"), self.actionResetSpecies.trigger)
        QtCore.QObject.connect(self.computeSensitivitiesButton, QtCore.SIGNAL("clicked()"), self.actionComputeSensitivities.trigger)
        QtCore.QObject.connect(self.simulateButtonParams, QtCore.SIGNAL("clicked()"), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.resetButtonParams, QtCore.SIGNAL("clicked()"), self.actionResetParameters.trigger)
        QtCore.QObject.connect(self.checkBoxUseMeasuredTimepoints, QtCore.SIGNAL("toggled(bool)"), self.lineEditStartTime.setDisabled)
        QtCore.QObject.connect(self.checkBoxUseMeasuredTimepoints, QtCore.SIGNAL("toggled(bool)"), self.lineEditEndTime.setDisabled)
        QtCore.QObject.connect(self.checkBoxUseMeasuredTimepoints, QtCore.SIGNAL("toggled(bool)"), self.lineEditNumIntervals.setDisabled)
        QtCore.QObject.connect(self.checkBoxUseMeasuredTimepoints, QtCore.SIGNAL("toggled(bool)"), self.labelStartTime.setDisabled)
        QtCore.QObject.connect(self.checkBoxUseMeasuredTimepoints, QtCore.SIGNAL("toggled(bool)"), self.labelEndTime.setDisabled)
        QtCore.QObject.connect(self.checkBoxUseMeasuredTimepoints, QtCore.SIGNAL("toggled(bool)"), self.labelNumIntervals.setDisabled)
        QtCore.QObject.connect(self.estimateParamsButton, QtCore.SIGNAL("clicked()"), self.actionEstimateParameterValues.trigger)
        QtCore.QObject.connect(self.perturbExpDataPushButton, QtCore.SIGNAL("clicked()"), self.actionPerturbExperimentalData.trigger)
        QtCore.QObject.connect(self.checkBoxUseMeasuredTimepoints, QtCore.SIGNAL("toggled(bool)"), self.labelIntervalSize.setDisabled)
        QtCore.QObject.connect(self.checkBoxUseMeasuredTimepoints, QtCore.SIGNAL("toggled(bool)"), self.lineEditIntervalSize.setDisabled)
        QtCore.QObject.connect(self.simulateButtonSettings, QtCore.SIGNAL("clicked()"), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.buttonDeselectAllSensitivity, QtCore.SIGNAL("clicked()"), self.actionDeselectAllParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonInvertSelectionSensitivity, QtCore.SIGNAL("clicked()"), self.actionInvertSelectionOfParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonSelectAllSensitivity, QtCore.SIGNAL("clicked()"), self.actionSelectAllParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonDeselectAllParamEst, QtCore.SIGNAL("clicked()"), self.actionDeselect_All_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonInvertSelectionParamEst, QtCore.SIGNAL("clicked()"), self.actionInvert_Selection_of_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonSelectAllParamEst, QtCore.SIGNAL("clicked()"), self.actionSelect_All_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonParamSetDuplicate, QtCore.SIGNAL("clicked()"), self.actionDuplicate_Parameter_Set.trigger)
        QtCore.QObject.connect(self.buttonParamSetNew, QtCore.SIGNAL("clicked()"), self.actionNew_Parameter_Set.trigger)
        QtCore.QObject.connect(self.buttonParamSetRemove, QtCore.SIGNAL("clicked()"), self.actionRemove_Parameter_Set.trigger)
        QtCore.QMetaObject.connectSlotsByName(SimulationWorkbench)

    def retranslateUi(self, SimulationWorkbench):
        SimulationWorkbench.setWindowTitle(QtGui.QApplication.translate("SimulationWorkbench", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButtonSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Reset Species", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSpecies), QtGui.QApplication.translate("SimulationWorkbench", "&Species", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonParams.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButtonParams.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Reset Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabParameters), QtGui.QApplication.translate("SimulationWorkbench", "&Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonParamSetNew.setText(QtGui.QApplication.translate("SimulationWorkbench", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonParamSetDuplicate.setText(QtGui.QApplication.translate("SimulationWorkbench", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonParamSetRemove.setText(QtGui.QApplication.translate("SimulationWorkbench", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabParameterSets), QtGui.QApplication.translate("SimulationWorkbench", "Parameter Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAllSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAllSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelectionSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.computeSensitivitiesButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "Compute Sensitivities", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSensitivitiesText.setText(QtGui.QApplication.translate("SimulationWorkbench", "(If you want to compute sensitivities based on measured time points, got to the Settings tab.)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSensitivity), QtGui.QApplication.translate("SimulationWorkbench", "&Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAllParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAllParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelectionParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.estimateParamsButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "Identify Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabFit), QtGui.QApplication.translate("SimulationWorkbench", "&Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBrowseExpData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonImportExpData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlotExperimentalData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Plot Experimental Data", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonExpDataRemoveSelected.setText(QtGui.QApplication.translate("SimulationWorkbench", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.experimentalDataToolBox.setItemText(self.experimentalDataToolBox.indexOf(self.pageMainFeatures), QtGui.QApplication.translate("SimulationWorkbench", "Main Features", None, QtGui.QApplication.UnicodeUTF8))
        self.perturbExpDataLabel.setText(QtGui.QApplication.translate("SimulationWorkbench", "Perturbation Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.perturbExpDataDoubleSpinBox.setSuffix(QtGui.QApplication.translate("SimulationWorkbench", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.perturbExpDataPushButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "Perturb Experimental Data", None, QtGui.QApplication.UnicodeUTF8))
        self.experimentalDataToolBox.setItemText(self.experimentalDataToolBox.indexOf(self.pageAdvancedFeatures), QtGui.QApplication.translate("SimulationWorkbench", "Advanced Features", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabExperimentalData), QtGui.QApplication.translate("SimulationWorkbench", "Experimental &Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "General Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Select the computation backend BioParkin uses for simulations, sensitivity calculations, etc. (FORTRAN code generation is available here for compatibility and debugging reasons.)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Select the computation backend BioParkin uses for simulations, sensitivity calculations, etc. (FORTRAN code generation is available here for compatibility and debugging reasons.)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setText(QtGui.QApplication.translate("SimulationWorkbench", "Computation Backend:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBackendSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "PARKINcpp", None, QtGui.QApplication.UnicodeUTF8))
        self.autoRefreshCheckBox.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Automatically Simulate on Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPlotExpData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Include Experimental Data in Simulation Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTimes.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "Time Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStartTime.setText(QtGui.QApplication.translate("SimulationWorkbench", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEndTime.setText(QtGui.QApplication.translate("SimulationWorkbench", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTimeUnit.setText(QtGui.QApplication.translate("SimulationWorkbench", "Time Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNumIntervals.setText(QtGui.QApplication.translate("SimulationWorkbench", "# Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseMeasuredTimepoints.setText(QtGui.QApplication.translate("SimulationWorkbench", "Use Measured Timepoints (taken from Currently Loaded Experimental Data)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIntervalSize.setText(QtGui.QApplication.translate("SimulationWorkbench", "Interval Size", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTolerances.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "Expert Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance (RTOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Absolute Tolerance (ATOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Required Tolerance (XTOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonSettings.setText(QtGui.QApplication.translate("SimulationWorkbench", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSettings), QtGui.QApplication.translate("SimulationWorkbench", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Simulate with current settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveData.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveData.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveData.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSavePlot.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSavePlot.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Save Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSavePlot.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoRefresh.setText(QtGui.QApplication.translate("SimulationWorkbench", "Auto Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoRefresh.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Simulation will occur automatically if enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoRefresh.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivities.setText(QtGui.QApplication.translate("SimulationWorkbench", "Compute Sensitivities", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivities.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Compute sensitivities of the currently selected Species", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivities.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Reset Species", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetSpecies.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Resets all Species values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetParameters.setText(QtGui.QApplication.translate("SimulationWorkbench", "Reset Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetParameters.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Resets all Parameter values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEstimateParameterValues.setText(QtGui.QApplication.translate("SimulationWorkbench", "Estimate Parameter Values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEstimateParameterValues.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Starts the parameter value estimation process", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPerturbExperimentalData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Perturb Experimental Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPerturbExperimentalData.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Perturbs the loaded experimental data by the given percentage.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAllParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselectAllParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvertSelectionOfParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection of Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselect_All_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert_Selection_of_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection of Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "New Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Create a new Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "Duplicate Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Create a new Parameter Set by duplicating the selected one", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "Remove Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Remove selected Parameter Set", None, QtGui.QApplication.UnicodeUTF8))

