# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tom/Work/Eric4/BioPARKIN/src/simulationworkbench/simulationworkbench_v4.ui'
#
# Created: Tue Jul 17 14:29:57 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SimulationWorkbench(object):
    def setupUi(self, SimulationWorkbench):
        SimulationWorkbench.setObjectName("SimulationWorkbench")
        SimulationWorkbench.resize(724, 842)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SimulationWorkbench.sizePolicy().hasHeightForWidth())
        SimulationWorkbench.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(SimulationWorkbench)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.actionTabWidget = QtGui.QTabWidget(SimulationWorkbench)
        self.actionTabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.actionTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.actionTabWidget.setObjectName("actionTabWidget")
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabSettings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.tabSettings)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelComputationBackend = QtGui.QLabel(self.groupBox)
        self.labelComputationBackend.setObjectName("labelComputationBackend")
        self.horizontalLayout_2.addWidget(self.labelComputationBackend)
        self.comboBoxBackendSelect = QtGui.QComboBox(self.groupBox)
        self.comboBoxBackendSelect.setObjectName("comboBoxBackendSelect")
        self.comboBoxBackendSelect.addItem("")
        self.comboBoxBackendSelect.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxBackendSelect)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.checkBoxPlotExpData = QtGui.QCheckBox(self.groupBox)
        self.checkBoxPlotExpData.setObjectName("checkBoxPlotExpData")
        self.verticalLayout_7.addWidget(self.checkBoxPlotExpData)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBoxTimes = QtGui.QGroupBox(self.tabSettings)
        self.groupBoxTimes.setObjectName("groupBoxTimes")
        self.gridLayout = QtGui.QGridLayout(self.groupBoxTimes)
        self.gridLayout.setObjectName("gridLayout")
        self.labelStartTime = QtGui.QLabel(self.groupBoxTimes)
        self.labelStartTime.setObjectName("labelStartTime")
        self.gridLayout.addWidget(self.labelStartTime, 0, 0, 1, 1)
        self.lineEditStartTime = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditStartTime.setText("")
        self.lineEditStartTime.setObjectName("lineEditStartTime")
        self.gridLayout.addWidget(self.lineEditStartTime, 0, 1, 1, 1)
        self.labelEndTime = QtGui.QLabel(self.groupBoxTimes)
        self.labelEndTime.setObjectName("labelEndTime")
        self.gridLayout.addWidget(self.labelEndTime, 1, 0, 1, 1)
        self.lineEditEndTime = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditEndTime.setText("")
        self.lineEditEndTime.setObjectName("lineEditEndTime")
        self.gridLayout.addWidget(self.lineEditEndTime, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBoxTimes)
        self.groupBoxPlot = QtGui.QGroupBox(self.tabSettings)
        self.groupBoxPlot.setObjectName("groupBoxPlot")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupBoxPlot)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelTimeUnit = QtGui.QLabel(self.groupBoxPlot)
        self.labelTimeUnit.setObjectName("labelTimeUnit")
        self.horizontalLayout_12.addWidget(self.labelTimeUnit)
        self.lineEditTimeUnit = QtGui.QLineEdit(self.groupBoxPlot)
        self.lineEditTimeUnit.setText("")
        self.lineEditTimeUnit.setObjectName("lineEditTimeUnit")
        self.horizontalLayout_12.addWidget(self.lineEditTimeUnit)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addWidget(self.groupBoxPlot)
        self.groupBoxTolerances = QtGui.QGroupBox(self.tabSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTolerances.sizePolicy().hasHeightForWidth())
        self.groupBoxTolerances.setSizePolicy(sizePolicy)
        self.groupBoxTolerances.setFlat(False)
        self.groupBoxTolerances.setCheckable(False)
        self.groupBoxTolerances.setObjectName("groupBoxTolerances")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxTolerances)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelRTOL = QtGui.QLabel(self.groupBoxTolerances)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRTOL.sizePolicy().hasHeightForWidth())
        self.labelRTOL.setSizePolicy(sizePolicy)
        self.labelRTOL.setObjectName("labelRTOL")
        self.gridLayout_2.addWidget(self.labelRTOL, 0, 0, 1, 1)
        self.lineEditRTOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditRTOL.setText("")
        self.lineEditRTOL.setObjectName("lineEditRTOL")
        self.gridLayout_2.addWidget(self.lineEditRTOL, 0, 1, 1, 1)
        self.labelATOL = QtGui.QLabel(self.groupBoxTolerances)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelATOL.sizePolicy().hasHeightForWidth())
        self.labelATOL.setSizePolicy(sizePolicy)
        self.labelATOL.setObjectName("labelATOL")
        self.gridLayout_2.addWidget(self.labelATOL, 1, 0, 1, 1)
        self.lineEditATOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditATOL.setText("")
        self.lineEditATOL.setObjectName("lineEditATOL")
        self.gridLayout_2.addWidget(self.lineEditATOL, 1, 1, 1, 1)
        self.labelXTOL = QtGui.QLabel(self.groupBoxTolerances)
        self.labelXTOL.setObjectName("labelXTOL")
        self.gridLayout_2.addWidget(self.labelXTOL, 2, 0, 1, 1)
        self.lineEditXTOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditXTOL.setObjectName("lineEditXTOL")
        self.gridLayout_2.addWidget(self.lineEditXTOL, 2, 1, 1, 1)
        self.labelMaxNumNewtonSteps = QtGui.QLabel(self.groupBoxTolerances)
        self.labelMaxNumNewtonSteps.setObjectName("labelMaxNumNewtonSteps")
        self.gridLayout_2.addWidget(self.labelMaxNumNewtonSteps, 3, 0, 1, 1)
        self.lineEditMaxNumNewtonSteps = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditMaxNumNewtonSteps.setText("")
        self.lineEditMaxNumNewtonSteps.setObjectName("lineEditMaxNumNewtonSteps")
        self.gridLayout_2.addWidget(self.lineEditMaxNumNewtonSteps, 3, 1, 1, 1)
        self.labelLPOS = QtGui.QLabel(self.groupBoxTolerances)
        self.labelLPOS.setObjectName("labelLPOS")
        self.gridLayout_2.addWidget(self.labelLPOS, 4, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.comboBoxParameterConstraintsSelect = QtGui.QComboBox(self.groupBoxTolerances)
        self.comboBoxParameterConstraintsSelect.setEnabled(True)
        self.comboBoxParameterConstraintsSelect.setObjectName("comboBoxParameterConstraintsSelect")
        self.comboBoxParameterConstraintsSelect.addItem("")
        self.comboBoxParameterConstraintsSelect.addItem("")
        self.comboBoxParameterConstraintsSelect.addItem("")
        self.comboBoxParameterConstraintsSelect.addItem("")
        self.comboBoxParameterConstraintsSelect.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBoxParameterConstraintsSelect)
        self.labelConstLowerBound = QtGui.QLabel(self.groupBoxTolerances)
        self.labelConstLowerBound.setEnabled(False)
        self.labelConstLowerBound.setObjectName("labelConstLowerBound")
        self.horizontalLayout_21.addWidget(self.labelConstLowerBound)
        self.lineEditConstLowerBound = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditConstLowerBound.setEnabled(False)
        self.lineEditConstLowerBound.setObjectName("lineEditConstLowerBound")
        self.horizontalLayout_21.addWidget(self.lineEditConstLowerBound)
        self.labelConstUpperBound = QtGui.QLabel(self.groupBoxTolerances)
        self.labelConstUpperBound.setEnabled(False)
        self.labelConstUpperBound.setObjectName("labelConstUpperBound")
        self.horizontalLayout_21.addWidget(self.labelConstUpperBound)
        self.lineEditConstUpperBound = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditConstUpperBound.setEnabled(False)
        self.lineEditConstUpperBound.setObjectName("lineEditConstUpperBound")
        self.horizontalLayout_21.addWidget(self.lineEditConstUpperBound)
        self.checkBoxParameterConstraintsPerParam = QtGui.QCheckBox(self.groupBoxTolerances)
        self.checkBoxParameterConstraintsPerParam.setObjectName("checkBoxParameterConstraintsPerParam")
        self.horizontalLayout_21.addWidget(self.checkBoxParameterConstraintsPerParam)
        self.gridLayout_2.addLayout(self.horizontalLayout_21, 4, 1, 1, 1)
        self.labelJACGEN = QtGui.QLabel(self.groupBoxTolerances)
        self.labelJACGEN.setObjectName("labelJACGEN")
        self.gridLayout_2.addWidget(self.labelJACGEN, 5, 0, 1, 1)
        self.comboBoxJacobianSelect = QtGui.QComboBox(self.groupBoxTolerances)
        self.comboBoxJacobianSelect.setObjectName("comboBoxJacobianSelect")
        self.comboBoxJacobianSelect.addItem("")
        self.comboBoxJacobianSelect.addItem("")
        self.comboBoxJacobianSelect.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxJacobianSelect, 5, 1, 1, 1)
        self.labelNONLIN = QtGui.QLabel(self.groupBoxTolerances)
        self.labelNONLIN.setObjectName("labelNONLIN")
        self.gridLayout_2.addWidget(self.labelNONLIN, 6, 0, 1, 1)
        self.comboBoxProblemTypeSelect = QtGui.QComboBox(self.groupBoxTolerances)
        self.comboBoxProblemTypeSelect.setObjectName("comboBoxProblemTypeSelect")
        self.comboBoxProblemTypeSelect.addItem("")
        self.comboBoxProblemTypeSelect.addItem("")
        self.comboBoxProblemTypeSelect.addItem("")
        self.comboBoxProblemTypeSelect.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxProblemTypeSelect, 6, 1, 1, 1)
        self.labelRSCAL = QtGui.QLabel(self.groupBoxTolerances)
        self.labelRSCAL.setObjectName("labelRSCAL")
        self.gridLayout_2.addWidget(self.labelRSCAL, 7, 0, 1, 1)
        self.comboBoxResidualScalingSelect = QtGui.QComboBox(self.groupBoxTolerances)
        self.comboBoxResidualScalingSelect.setObjectName("comboBoxResidualScalingSelect")
        self.comboBoxResidualScalingSelect.addItem("")
        self.comboBoxResidualScalingSelect.addItem("")
        self.comboBoxResidualScalingSelect.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxResidualScalingSelect, 7, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBoxTolerances)
        spacerItem1 = QtGui.QSpacerItem(20, 272, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.simulateButtonSettings = QtGui.QPushButton(self.tabSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButtonSettings.sizePolicy().hasHeightForWidth())
        self.simulateButtonSettings.setSizePolicy(sizePolicy)
        self.simulateButtonSettings.setObjectName("simulateButtonSettings")
        self.horizontalLayout_11.addWidget(self.simulateButtonSettings)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.actionTabWidget.addTab(self.tabSettings, "")
        self.tabSpecies = QtGui.QWidget()
        self.tabSpecies.setObjectName("tabSpecies")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tabSpecies)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.speciesTableView = QtGui.QTableView(self.tabSpecies)
        self.speciesTableView.setObjectName("speciesTableView")
        self.verticalLayout_5.addWidget(self.speciesTableView)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonInitializeThresholdsSpecies = QtGui.QPushButton(self.tabSpecies)
        self.buttonInitializeThresholdsSpecies.setObjectName("buttonInitializeThresholdsSpecies")
        self.horizontalLayout_5.addWidget(self.buttonInitializeThresholdsSpecies)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.simulateButtonSpecies = QtGui.QPushButton(self.tabSpecies)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButtonSpecies.sizePolicy().hasHeightForWidth())
        self.simulateButtonSpecies.setSizePolicy(sizePolicy)
        self.simulateButtonSpecies.setObjectName("simulateButtonSpecies")
        self.horizontalLayout_5.addWidget(self.simulateButtonSpecies)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.actionTabWidget.addTab(self.tabSpecies, "")
        self.tabParameters = QtGui.QWidget()
        self.tabParameters.setObjectName("tabParameters")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tabParameters)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.parametersTableView = QtGui.QTableView(self.tabParameters)
        self.parametersTableView.setObjectName("parametersTableView")
        self.verticalLayout.addWidget(self.parametersTableView)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttonInitializeThresholdsParameters = QtGui.QPushButton(self.tabParameters)
        self.buttonInitializeThresholdsParameters.setObjectName("buttonInitializeThresholdsParameters")
        self.horizontalLayout_7.addWidget(self.buttonInitializeThresholdsParameters)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.simulateButtonParams = QtGui.QPushButton(self.tabParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButtonParams.sizePolicy().hasHeightForWidth())
        self.simulateButtonParams.setSizePolicy(sizePolicy)
        self.simulateButtonParams.setObjectName("simulateButtonParams")
        self.horizontalLayout_7.addWidget(self.simulateButtonParams)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.actionTabWidget.addTab(self.tabParameters, "")
        self.tabParameterSets = QtGui.QWidget()
        self.tabParameterSets.setObjectName("tabParameterSets")
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.tabParameterSets)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.parameterSetsTableView = QtGui.QTableView(self.tabParameterSets)
        self.parameterSetsTableView.setObjectName("parameterSetsTableView")
        self.verticalLayout_13.addWidget(self.parameterSetsTableView)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.buttonParamSetDuplicate = QtGui.QPushButton(self.tabParameterSets)
        self.buttonParamSetDuplicate.setObjectName("buttonParamSetDuplicate")
        self.horizontalLayout_17.addWidget(self.buttonParamSetDuplicate)
        self.buttonParamSetRemove = QtGui.QPushButton(self.tabParameterSets)
        self.buttonParamSetRemove.setObjectName("buttonParamSetRemove")
        self.horizontalLayout_17.addWidget(self.buttonParamSetRemove)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.simulateButtonParamSets = QtGui.QPushButton(self.tabParameterSets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButtonParamSets.sizePolicy().hasHeightForWidth())
        self.simulateButtonParamSets.setSizePolicy(sizePolicy)
        self.simulateButtonParamSets.setObjectName("simulateButtonParamSets")
        self.horizontalLayout_17.addWidget(self.simulateButtonParamSets)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_13)
        self.actionTabWidget.addTab(self.tabParameterSets, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dataBrowserTabWidget = QtGui.QTabWidget(self.tab)
        self.dataBrowserTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.dataBrowserTabWidget.setDocumentMode(False)
        self.dataBrowserTabWidget.setTabsClosable(True)
        self.dataBrowserTabWidget.setMovable(True)
        self.dataBrowserTabWidget.setObjectName("dataBrowserTabWidget")
        self.dataBrowserPlusTab = QtGui.QWidget()
        self.dataBrowserPlusTab.setObjectName("dataBrowserPlusTab")
        self.dataBrowserTabWidget.addTab(self.dataBrowserPlusTab, "")
        self.verticalLayout_6.addWidget(self.dataBrowserTabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonPlotAllData = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlotAllData.sizePolicy().hasHeightForWidth())
        self.buttonPlotAllData.setSizePolicy(sizePolicy)
        self.buttonPlotAllData.setObjectName("buttonPlotAllData")
        self.horizontalLayout_3.addWidget(self.buttonPlotAllData)
        self.buttonPlotSelectedData = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlotSelectedData.sizePolicy().hasHeightForWidth())
        self.buttonPlotSelectedData.setSizePolicy(sizePolicy)
        self.buttonPlotSelectedData.setObjectName("buttonPlotSelectedData")
        self.horizontalLayout_3.addWidget(self.buttonPlotSelectedData)
        self.checkBoxPlotExpDataDataBrowser = QtGui.QCheckBox(self.tab)
        self.checkBoxPlotExpDataDataBrowser.setObjectName("checkBoxPlotExpDataDataBrowser")
        self.horizontalLayout_3.addWidget(self.checkBoxPlotExpDataDataBrowser)
        spacerItem6 = QtGui.QSpacerItem(538, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_19.addLayout(self.verticalLayout_6)
        self.actionTabWidget.addTab(self.tab, "")
        self.tabSensitivity = QtGui.QWidget()
        self.tabSensitivity.setObjectName("tabSensitivity")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tabSensitivity)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSensitivitySelectParams = QtGui.QLabel(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSensitivitySelectParams.sizePolicy().hasHeightForWidth())
        self.labelSensitivitySelectParams.setSizePolicy(sizePolicy)
        self.labelSensitivitySelectParams.setObjectName("labelSensitivitySelectParams")
        self.verticalLayout_2.addWidget(self.labelSensitivitySelectParams)
        self.sensitivityTableView = QtGui.QTableView(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivityTableView.sizePolicy().hasHeightForWidth())
        self.sensitivityTableView.setSizePolicy(sizePolicy)
        self.sensitivityTableView.setObjectName("sensitivityTableView")
        self.verticalLayout_2.addWidget(self.sensitivityTableView)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.buttonSelectAllSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonSelectAllSensitivity.setObjectName("buttonSelectAllSensitivity")
        self.horizontalLayout_13.addWidget(self.buttonSelectAllSensitivity)
        self.buttonDeselectAllSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonDeselectAllSensitivity.setObjectName("buttonDeselectAllSensitivity")
        self.horizontalLayout_13.addWidget(self.buttonDeselectAllSensitivity)
        self.buttonInvertSelectionSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonInvertSelectionSensitivity.setObjectName("buttonInvertSelectionSensitivity")
        self.horizontalLayout_13.addWidget(self.buttonInvertSelectionSensitivity)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelSensitivitySelectSpecies = QtGui.QLabel(self.tabSensitivity)
        self.labelSensitivitySelectSpecies.setObjectName("labelSensitivitySelectSpecies")
        self.verticalLayout_8.addWidget(self.labelSensitivitySelectSpecies)
        self.tableViewSensitivitySpecies = QtGui.QTableView(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewSensitivitySpecies.sizePolicy().hasHeightForWidth())
        self.tableViewSensitivitySpecies.setSizePolicy(sizePolicy)
        self.tableViewSensitivitySpecies.setObjectName("tableViewSensitivitySpecies")
        self.verticalLayout_8.addWidget(self.tableViewSensitivitySpecies)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.buttonSelectAllSensitivitySpecies = QtGui.QPushButton(self.tabSensitivity)
        self.buttonSelectAllSensitivitySpecies.setObjectName("buttonSelectAllSensitivitySpecies")
        self.horizontalLayout_14.addWidget(self.buttonSelectAllSensitivitySpecies)
        self.buttonDeselectAllSensitivitySpecies = QtGui.QPushButton(self.tabSensitivity)
        self.buttonDeselectAllSensitivitySpecies.setObjectName("buttonDeselectAllSensitivitySpecies")
        self.horizontalLayout_14.addWidget(self.buttonDeselectAllSensitivitySpecies)
        self.buttonInvertSelectionSensitivitySpecies = QtGui.QPushButton(self.tabSensitivity)
        self.buttonInvertSelectionSensitivitySpecies.setObjectName("buttonInvertSelectionSensitivitySpecies")
        self.horizontalLayout_14.addWidget(self.buttonInvertSelectionSensitivitySpecies)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.tabSensitivity)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.computeSensitivityOverviewButton = QtGui.QPushButton(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.computeSensitivityOverviewButton.sizePolicy().hasHeightForWidth())
        self.computeSensitivityOverviewButton.setSizePolicy(sizePolicy)
        self.computeSensitivityOverviewButton.setCheckable(False)
        self.computeSensitivityOverviewButton.setObjectName("computeSensitivityOverviewButton")
        self.horizontalLayout_9.addWidget(self.computeSensitivityOverviewButton)
        self.computeDetailedSensitivitiesButton = QtGui.QPushButton(self.tabSensitivity)
        self.computeDetailedSensitivitiesButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.computeDetailedSensitivitiesButton.sizePolicy().hasHeightForWidth())
        self.computeDetailedSensitivitiesButton.setSizePolicy(sizePolicy)
        self.computeDetailedSensitivitiesButton.setObjectName("computeDetailedSensitivitiesButton")
        self.horizontalLayout_9.addWidget(self.computeDetailedSensitivitiesButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        self.actionTabWidget.addTab(self.tabSensitivity, "")
        self.tabFit = QtGui.QWidget()
        self.tabFit.setObjectName("tabFit")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.tabFit)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.estimateParamsTableView = QtGui.QTableView(self.tabFit)
        self.estimateParamsTableView.setObjectName("estimateParamsTableView")
        self.verticalLayout_3.addWidget(self.estimateParamsTableView)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.buttonSelectAllParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonSelectAllParamEst.setObjectName("buttonSelectAllParamEst")
        self.horizontalLayout_15.addWidget(self.buttonSelectAllParamEst)
        self.buttonDeselectAllParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonDeselectAllParamEst.setObjectName("buttonDeselectAllParamEst")
        self.horizontalLayout_15.addWidget(self.buttonDeselectAllParamEst)
        self.buttonInvertSelectionParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonInvertSelectionParamEst.setObjectName("buttonInvertSelectionParamEst")
        self.horizontalLayout_15.addWidget(self.buttonInvertSelectionParamEst)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.estimateParamsButton = QtGui.QPushButton(self.tabFit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estimateParamsButton.sizePolicy().hasHeightForWidth())
        self.estimateParamsButton.setSizePolicy(sizePolicy)
        self.estimateParamsButton.setObjectName("estimateParamsButton")
        self.horizontalLayout_15.addWidget(self.estimateParamsButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16.addLayout(self.verticalLayout_3)
        self.actionTabWidget.addTab(self.tabFit, "")
        self.horizontalLayout.addWidget(self.actionTabWidget)
        self.actionSimulate = QtGui.QAction(SimulationWorkbench)
        self.actionSimulate.setObjectName("actionSimulate")
        self.actionReset = QtGui.QAction(SimulationWorkbench)
        self.actionReset.setObjectName("actionReset")
        self.actionComputeSensitivityOverview = QtGui.QAction(SimulationWorkbench)
        self.actionComputeSensitivityOverview.setObjectName("actionComputeSensitivityOverview")
        self.actionResetSpecies = QtGui.QAction(SimulationWorkbench)
        self.actionResetSpecies.setObjectName("actionResetSpecies")
        self.actionResetParameters = QtGui.QAction(SimulationWorkbench)
        self.actionResetParameters.setObjectName("actionResetParameters")
        self.actionEstimateParameterValues = QtGui.QAction(SimulationWorkbench)
        self.actionEstimateParameterValues.setObjectName("actionEstimateParameterValues")
        self.actionPerturbExperimentalData = QtGui.QAction(SimulationWorkbench)
        self.actionPerturbExperimentalData.setObjectName("actionPerturbExperimentalData")
        self.actionSelectAllParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionSelectAllParametersForSensitivity.setObjectName("actionSelectAllParametersForSensitivity")
        self.actionDeselectAllParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionDeselectAllParametersForSensitivity.setObjectName("actionDeselectAllParametersForSensitivity")
        self.actionInvertSelectionOfParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionInvertSelectionOfParametersForSensitivity.setObjectName("actionInvertSelectionOfParametersForSensitivity")
        self.actionSelect_All_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionSelect_All_Parameters_for_Estimation.setObjectName("actionSelect_All_Parameters_for_Estimation")
        self.actionDeselect_All_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionDeselect_All_Parameters_for_Estimation.setObjectName("actionDeselect_All_Parameters_for_Estimation")
        self.actionInvert_Selection_of_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionInvert_Selection_of_Parameters_for_Estimation.setObjectName("actionInvert_Selection_of_Parameters_for_Estimation")
        self.actionNew_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionNew_Parameter_Set.setObjectName("actionNew_Parameter_Set")
        self.actionDuplicate_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionDuplicate_Parameter_Set.setObjectName("actionDuplicate_Parameter_Set")
        self.actionRemove_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionRemove_Parameter_Set.setObjectName("actionRemove_Parameter_Set")
        self.actionCompute_Detailed_Sensitivities = QtGui.QAction(SimulationWorkbench)
        self.actionCompute_Detailed_Sensitivities.setObjectName("actionCompute_Detailed_Sensitivities")
        self.actionSelectAllSpeciesForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionSelectAllSpeciesForSensitivity.setObjectName("actionSelectAllSpeciesForSensitivity")
        self.actionDeselectAllSpeciesForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionDeselectAllSpeciesForSensitivity.setObjectName("actionDeselectAllSpeciesForSensitivity")
        self.actionInvertSelectionOfSpeciesForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionInvertSelectionOfSpeciesForSensitivity.setObjectName("actionInvertSelectionOfSpeciesForSensitivity")

        self.retranslateUi(SimulationWorkbench)
        self.actionTabWidget.setCurrentIndex(0)
        self.dataBrowserTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.simulateButtonSpecies, QtCore.SIGNAL("clicked()"), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.computeSensitivityOverviewButton, QtCore.SIGNAL("clicked()"), self.actionComputeSensitivityOverview.trigger)
        QtCore.QObject.connect(self.simulateButtonParams, QtCore.SIGNAL("clicked()"), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.estimateParamsButton, QtCore.SIGNAL("clicked()"), self.actionEstimateParameterValues.trigger)
        QtCore.QObject.connect(self.simulateButtonSettings, QtCore.SIGNAL("clicked()"), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.buttonDeselectAllSensitivity, QtCore.SIGNAL("clicked()"), self.actionDeselectAllParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonInvertSelectionSensitivity, QtCore.SIGNAL("clicked()"), self.actionInvertSelectionOfParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonSelectAllSensitivity, QtCore.SIGNAL("clicked()"), self.actionSelectAllParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonDeselectAllParamEst, QtCore.SIGNAL("clicked()"), self.actionDeselect_All_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonInvertSelectionParamEst, QtCore.SIGNAL("clicked()"), self.actionInvert_Selection_of_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonSelectAllParamEst, QtCore.SIGNAL("clicked()"), self.actionSelect_All_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonParamSetDuplicate, QtCore.SIGNAL("clicked()"), self.actionDuplicate_Parameter_Set.trigger)
        QtCore.QObject.connect(self.buttonParamSetRemove, QtCore.SIGNAL("clicked()"), self.actionRemove_Parameter_Set.trigger)
        QtCore.QObject.connect(self.computeDetailedSensitivitiesButton, QtCore.SIGNAL("clicked()"), self.actionCompute_Detailed_Sensitivities.trigger)
        QtCore.QObject.connect(self.buttonDeselectAllSensitivitySpecies, QtCore.SIGNAL("clicked()"), self.actionDeselectAllSpeciesForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonInvertSelectionSensitivitySpecies, QtCore.SIGNAL("clicked()"), self.actionInvertSelectionOfSpeciesForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonSelectAllSensitivitySpecies, QtCore.SIGNAL("clicked()"), self.actionSelectAllSpeciesForSensitivity.trigger)
        QtCore.QObject.connect(self.simulateButtonParamSets, QtCore.SIGNAL("clicked()"), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.checkBoxParameterConstraintsPerParam, QtCore.SIGNAL("toggled(bool)"), self.comboBoxParameterConstraintsSelect.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(SimulationWorkbench)

    def retranslateUi(self, SimulationWorkbench):
        SimulationWorkbench.setWindowTitle(QtGui.QApplication.translate("SimulationWorkbench", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "General Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Select the computation backend BioParkin uses for simulations, sensitivity calculations, etc. (FORTRAN code generation is available here for compatibility and debugging reasons.)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Select the computation backend BioParkin uses for simulations, sensitivity calculations, etc. (FORTRAN code generation is available here for compatibility and debugging reasons.)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setText(QtGui.QApplication.translate("SimulationWorkbench", "Identification Backend:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBackendSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "Gauß-Newton (NLSCON)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBackendSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "Gauß-Newton (PARKIN)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPlotExpData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Include Experimental Data in Simulation Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTimes.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "Time Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStartTime.setText(QtGui.QApplication.translate("SimulationWorkbench", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEndTime.setText(QtGui.QApplication.translate("SimulationWorkbench", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxPlot.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "Plot Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTimeUnit.setText(QtGui.QApplication.translate("SimulationWorkbench", "Time Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTolerances.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "Expert Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance (RTOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Absolute Tolerance (ATOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Required Tolerance (XTOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMaxNumNewtonSteps.setText(QtGui.QApplication.translate("SimulationWorkbench", "Max. # Newton Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLPOS.setText(QtGui.QApplication.translate("SimulationWorkbench", "Parameter Constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxParameterConstraintsSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "no constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxParameterConstraintsSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "strictly positive (exponential transformation)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxParameterConstraintsSelect.setItemText(2, QtGui.QApplication.translate("SimulationWorkbench", "lower bound", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxParameterConstraintsSelect.setItemText(3, QtGui.QApplication.translate("SimulationWorkbench", "upper bound", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxParameterConstraintsSelect.setItemText(4, QtGui.QApplication.translate("SimulationWorkbench", "interval (combined lower and upper bound)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelConstLowerBound.setText(QtGui.QApplication.translate("SimulationWorkbench", "Lower Bound", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditConstLowerBound.setText(QtGui.QApplication.translate("SimulationWorkbench", "-inf", None, QtGui.QApplication.UnicodeUTF8))
        self.labelConstUpperBound.setText(QtGui.QApplication.translate("SimulationWorkbench", "Upper Bound", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditConstUpperBound.setText(QtGui.QApplication.translate("SimulationWorkbench", "inf", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxParameterConstraintsPerParam.setText(QtGui.QApplication.translate("SimulationWorkbench", "Constraints Per Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.labelJACGEN.setText(QtGui.QApplication.translate("SimulationWorkbench", "Jacobian", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxJacobianSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "Variational Equations", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxJacobianSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "Numerical Differentiation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxJacobianSelect.setItemText(2, QtGui.QApplication.translate("SimulationWorkbench", "Numerical Diff. with Feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNONLIN.setText(QtGui.QApplication.translate("SimulationWorkbench", "Problem Type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxProblemTypeSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxProblemTypeSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "mildly nonlinear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxProblemTypeSelect.setItemText(2, QtGui.QApplication.translate("SimulationWorkbench", "highly nonlinear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxProblemTypeSelect.setItemText(3, QtGui.QApplication.translate("SimulationWorkbench", "extremely nonlinear", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRSCAL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Residual Scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResidualScalingSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "no extra scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResidualScalingSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "relative scaling (w.r.t. upper/lower machine bound)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResidualScalingSelect.setItemText(2, QtGui.QApplication.translate("SimulationWorkbench", "absolute scaling (w.r.t. upper/lower machine bound)", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonSettings.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSettings), QtGui.QApplication.translate("SimulationWorkbench", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInitializeThresholdsSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Initialize Thresholds", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSpecies), QtGui.QApplication.translate("SimulationWorkbench", "&Species", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInitializeThresholdsParameters.setText(QtGui.QApplication.translate("SimulationWorkbench", "Initialize Thresholds", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonParams.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabParameters), QtGui.QApplication.translate("SimulationWorkbench", "&Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonParamSetDuplicate.setText(QtGui.QApplication.translate("SimulationWorkbench", "Duplicate Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonParamSetRemove.setText(QtGui.QApplication.translate("SimulationWorkbench", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonParamSets.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabParameterSets), QtGui.QApplication.translate("SimulationWorkbench", "Parameter Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBrowserTabWidget.setTabText(self.dataBrowserTabWidget.indexOf(self.dataBrowserPlusTab), QtGui.QApplication.translate("SimulationWorkbench", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlotAllData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Plot All Data Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlotSelectedData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Plot Selected Data Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPlotExpDataDataBrowser.setText(QtGui.QApplication.translate("SimulationWorkbench", "Include Experimental Data in Simulation Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tab), QtGui.QApplication.translate("SimulationWorkbench", "Data Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSensitivitySelectParams.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAllSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAllSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelectionSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSensitivitySelectSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select Species", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAllSensitivitySpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAllSensitivitySpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelectionSensitivitySpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.computeSensitivityOverviewButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "Sensitivity &Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.computeDetailedSensitivitiesButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Detailed Sensitivities", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSensitivity), QtGui.QApplication.translate("SimulationWorkbench", "&Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAllParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAllParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelectionParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.estimateParamsButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Identify Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabFit), QtGui.QApplication.translate("SimulationWorkbench", "&Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Simulate with current settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivityOverview.setText(QtGui.QApplication.translate("SimulationWorkbench", "Compute Sensitivity Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivityOverview.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Compute the sensitivitiy overview (sensitivity trajectories) of the currently selected Species", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivityOverview.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Reset Species", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetSpecies.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Resets all Species values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetParameters.setText(QtGui.QApplication.translate("SimulationWorkbench", "Reset Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetParameters.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Resets all Parameter values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEstimateParameterValues.setText(QtGui.QApplication.translate("SimulationWorkbench", "Estimate Parameter Values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEstimateParameterValues.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Starts the parameter value estimation process", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPerturbExperimentalData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Perturb Experimental Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPerturbExperimentalData.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Perturbs the loaded experimental data by the given percentage.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAllParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselectAllParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvertSelectionOfParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection of Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselect_All_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert_Selection_of_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection of Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "New Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Create a new Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "Duplicate Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Create a new Parameter Set by duplicating the selected one", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "Remove Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Remove selected Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompute_Detailed_Sensitivities.setText(QtGui.QApplication.translate("SimulationWorkbench", "Compute Detailed Sensitivities", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompute_Detailed_Sensitivities.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Compute the sensitivities of the selected parameters at given timepoints.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompute_Detailed_Sensitivities.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAllSpeciesForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select all Species for Sensitivity Computation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselectAllSpeciesForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect all Species for Sensitivity Calculation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvertSelectionOfSpeciesForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert the selection of Species for Sensitivity Calculation", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SimulationWorkbench = QtGui.QWidget()
    ui = Ui_SimulationWorkbench()
    ui.setupUi(SimulationWorkbench)
    SimulationWorkbench.show()
    sys.exit(app.exec_())

