# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\workspace\bioparkin\src\simulationworkbench\simulationworkbench_v4.ui'
#
# Created: Fri Sep 16 10:39:39 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SimulationWorkbench(object):
    def setupUi(self, SimulationWorkbench):
        SimulationWorkbench.setObjectName(_fromUtf8("SimulationWorkbench"))
        SimulationWorkbench.resize(724, 842)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SimulationWorkbench.sizePolicy().hasHeightForWidth())
        SimulationWorkbench.setSizePolicy(sizePolicy)
        SimulationWorkbench.setWindowTitle(QtGui.QApplication.translate("SimulationWorkbench", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout = QtGui.QHBoxLayout(SimulationWorkbench)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.actionTabWidget = QtGui.QTabWidget(SimulationWorkbench)
        self.actionTabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.actionTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.actionTabWidget.setObjectName(_fromUtf8("actionTabWidget"))
        self.tabSpecies = QtGui.QWidget()
        self.tabSpecies.setObjectName(_fromUtf8("tabSpecies"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tabSpecies)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.speciesTableView = QtGui.QTableView(self.tabSpecies)
        self.speciesTableView.setObjectName(_fromUtf8("speciesTableView"))
        self.verticalLayout_5.addWidget(self.speciesTableView)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.buttonInitializeThresholdsSpecies = QtGui.QPushButton(self.tabSpecies)
        self.buttonInitializeThresholdsSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Initialize Thresholds", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInitializeThresholdsSpecies.setObjectName(_fromUtf8("buttonInitializeThresholdsSpecies"))
        self.horizontalLayout_5.addWidget(self.buttonInitializeThresholdsSpecies)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.simulateButtonSpecies = QtGui.QPushButton(self.tabSpecies)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButtonSpecies.sizePolicy().hasHeightForWidth())
        self.simulateButtonSpecies.setSizePolicy(sizePolicy)
        self.simulateButtonSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonSpecies.setObjectName(_fromUtf8("simulateButtonSpecies"))
        self.horizontalLayout_5.addWidget(self.simulateButtonSpecies)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.actionTabWidget.addTab(self.tabSpecies, _fromUtf8(""))
        self.tabParameters = QtGui.QWidget()
        self.tabParameters.setObjectName(_fromUtf8("tabParameters"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tabParameters)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.parametersTableView = QtGui.QTableView(self.tabParameters)
        self.parametersTableView.setObjectName(_fromUtf8("parametersTableView"))
        self.verticalLayout.addWidget(self.parametersTableView)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.buttonInitializeThresholdsParameters = QtGui.QPushButton(self.tabParameters)
        self.buttonInitializeThresholdsParameters.setText(QtGui.QApplication.translate("SimulationWorkbench", "Initialize Thresholds", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInitializeThresholdsParameters.setObjectName(_fromUtf8("buttonInitializeThresholdsParameters"))
        self.horizontalLayout_7.addWidget(self.buttonInitializeThresholdsParameters)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.simulateButtonParams = QtGui.QPushButton(self.tabParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButtonParams.sizePolicy().hasHeightForWidth())
        self.simulateButtonParams.setSizePolicy(sizePolicy)
        self.simulateButtonParams.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonParams.setObjectName(_fromUtf8("simulateButtonParams"))
        self.horizontalLayout_7.addWidget(self.simulateButtonParams)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.actionTabWidget.addTab(self.tabParameters, _fromUtf8(""))
        self.tabParameterSets = QtGui.QWidget()
        self.tabParameterSets.setObjectName(_fromUtf8("tabParameterSets"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.tabParameterSets)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.parameterSetsTableView = QtGui.QTableView(self.tabParameterSets)
        self.parameterSetsTableView.setObjectName(_fromUtf8("parameterSetsTableView"))
        self.verticalLayout_13.addWidget(self.parameterSetsTableView)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.buttonParamSetNew = QtGui.QPushButton(self.tabParameterSets)
        self.buttonParamSetNew.setText(QtGui.QApplication.translate("SimulationWorkbench", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonParamSetNew.setObjectName(_fromUtf8("buttonParamSetNew"))
        self.horizontalLayout_17.addWidget(self.buttonParamSetNew)
        self.buttonParamSetDuplicate = QtGui.QPushButton(self.tabParameterSets)
        self.buttonParamSetDuplicate.setText(QtGui.QApplication.translate("SimulationWorkbench", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonParamSetDuplicate.setObjectName(_fromUtf8("buttonParamSetDuplicate"))
        self.horizontalLayout_17.addWidget(self.buttonParamSetDuplicate)
        self.buttonParamSetRemove = QtGui.QPushButton(self.tabParameterSets)
        self.buttonParamSetRemove.setText(QtGui.QApplication.translate("SimulationWorkbench", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonParamSetRemove.setObjectName(_fromUtf8("buttonParamSetRemove"))
        self.horizontalLayout_17.addWidget(self.buttonParamSetRemove)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_13)
        self.actionTabWidget.addTab(self.tabParameterSets, _fromUtf8(""))
        self.tabSensitivity = QtGui.QWidget()
        self.tabSensitivity.setObjectName(_fromUtf8("tabSensitivity"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tabSensitivity)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelSensitivitySelectParams = QtGui.QLabel(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSensitivitySelectParams.sizePolicy().hasHeightForWidth())
        self.labelSensitivitySelectParams.setSizePolicy(sizePolicy)
        self.labelSensitivitySelectParams.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSensitivitySelectParams.setObjectName(_fromUtf8("labelSensitivitySelectParams"))
        self.verticalLayout_2.addWidget(self.labelSensitivitySelectParams)
        self.sensitivityTableView = QtGui.QTableView(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivityTableView.sizePolicy().hasHeightForWidth())
        self.sensitivityTableView.setSizePolicy(sizePolicy)
        self.sensitivityTableView.setObjectName(_fromUtf8("sensitivityTableView"))
        self.verticalLayout_2.addWidget(self.sensitivityTableView)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.buttonSelectAllSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonSelectAllSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAllSensitivity.setObjectName(_fromUtf8("buttonSelectAllSensitivity"))
        self.horizontalLayout_13.addWidget(self.buttonSelectAllSensitivity)
        self.buttonDeselectAllSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonDeselectAllSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAllSensitivity.setObjectName(_fromUtf8("buttonDeselectAllSensitivity"))
        self.horizontalLayout_13.addWidget(self.buttonDeselectAllSensitivity)
        self.buttonInvertSelectionSensitivity = QtGui.QPushButton(self.tabSensitivity)
        self.buttonInvertSelectionSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelectionSensitivity.setObjectName(_fromUtf8("buttonInvertSelectionSensitivity"))
        self.horizontalLayout_13.addWidget(self.buttonInvertSelectionSensitivity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.labelSensitivitySelectSpecies = QtGui.QLabel(self.tabSensitivity)
        self.labelSensitivitySelectSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select Species", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSensitivitySelectSpecies.setObjectName(_fromUtf8("labelSensitivitySelectSpecies"))
        self.verticalLayout_8.addWidget(self.labelSensitivitySelectSpecies)
        self.tableViewSensitivitySpecies = QtGui.QTableView(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewSensitivitySpecies.sizePolicy().hasHeightForWidth())
        self.tableViewSensitivitySpecies.setSizePolicy(sizePolicy)
        self.tableViewSensitivitySpecies.setObjectName(_fromUtf8("tableViewSensitivitySpecies"))
        self.verticalLayout_8.addWidget(self.tableViewSensitivitySpecies)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.buttonSelectAllSensitivitySpecies = QtGui.QPushButton(self.tabSensitivity)
        self.buttonSelectAllSensitivitySpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAllSensitivitySpecies.setObjectName(_fromUtf8("buttonSelectAllSensitivitySpecies"))
        self.horizontalLayout_14.addWidget(self.buttonSelectAllSensitivitySpecies)
        self.buttonDeselectAllSensitivitySpecies = QtGui.QPushButton(self.tabSensitivity)
        self.buttonDeselectAllSensitivitySpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAllSensitivitySpecies.setObjectName(_fromUtf8("buttonDeselectAllSensitivitySpecies"))
        self.horizontalLayout_14.addWidget(self.buttonDeselectAllSensitivitySpecies)
        self.buttonInvertSelectionSensitivitySpecies = QtGui.QPushButton(self.tabSensitivity)
        self.buttonInvertSelectionSensitivitySpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelectionSensitivitySpecies.setObjectName(_fromUtf8("buttonInvertSelectionSensitivitySpecies"))
        self.horizontalLayout_14.addWidget(self.buttonInvertSelectionSensitivitySpecies)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.tabSensitivity)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_9.addWidget(self.line)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.computeSensitivityOverviewButton = QtGui.QPushButton(self.tabSensitivity)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.computeSensitivityOverviewButton.sizePolicy().hasHeightForWidth())
        self.computeSensitivityOverviewButton.setSizePolicy(sizePolicy)
        self.computeSensitivityOverviewButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "Sensitivity Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.computeSensitivityOverviewButton.setCheckable(False)
        self.computeSensitivityOverviewButton.setObjectName(_fromUtf8("computeSensitivityOverviewButton"))
        self.horizontalLayout_9.addWidget(self.computeSensitivityOverviewButton)
        self.computeDetailedSensitivitiesButton = QtGui.QPushButton(self.tabSensitivity)
        self.computeDetailedSensitivitiesButton.setEnabled(False)
        self.computeDetailedSensitivitiesButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "Detailed Sensitivities", None, QtGui.QApplication.UnicodeUTF8))
        self.computeDetailedSensitivitiesButton.setObjectName(_fromUtf8("computeDetailedSensitivitiesButton"))
        self.horizontalLayout_9.addWidget(self.computeDetailedSensitivitiesButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        self.actionTabWidget.addTab(self.tabSensitivity, _fromUtf8(""))
        self.tabFit = QtGui.QWidget()
        self.tabFit.setObjectName(_fromUtf8("tabFit"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.tabFit)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.estimateParamsTableView = QtGui.QTableView(self.tabFit)
        self.estimateParamsTableView.setObjectName(_fromUtf8("estimateParamsTableView"))
        self.verticalLayout_3.addWidget(self.estimateParamsTableView)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.buttonSelectAllParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonSelectAllParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSelectAllParamEst.setObjectName(_fromUtf8("buttonSelectAllParamEst"))
        self.horizontalLayout_15.addWidget(self.buttonSelectAllParamEst)
        self.buttonDeselectAllParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonDeselectAllParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeselectAllParamEst.setObjectName(_fromUtf8("buttonDeselectAllParamEst"))
        self.horizontalLayout_15.addWidget(self.buttonDeselectAllParamEst)
        self.buttonInvertSelectionParamEst = QtGui.QPushButton(self.tabFit)
        self.buttonInvertSelectionParamEst.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInvertSelectionParamEst.setObjectName(_fromUtf8("buttonInvertSelectionParamEst"))
        self.horizontalLayout_15.addWidget(self.buttonInvertSelectionParamEst)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.estimateParamsButton = QtGui.QPushButton(self.tabFit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estimateParamsButton.sizePolicy().hasHeightForWidth())
        self.estimateParamsButton.setSizePolicy(sizePolicy)
        self.estimateParamsButton.setText(QtGui.QApplication.translate("SimulationWorkbench", "Identify Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.estimateParamsButton.setObjectName(_fromUtf8("estimateParamsButton"))
        self.horizontalLayout_15.addWidget(self.estimateParamsButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16.addLayout(self.verticalLayout_3)
        self.actionTabWidget.addTab(self.tabFit, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.dataBrowserTabWidget = QtGui.QTabWidget(self.tab)
        self.dataBrowserTabWidget.setDocumentMode(False)
        self.dataBrowserTabWidget.setTabsClosable(True)
        self.dataBrowserTabWidget.setMovable(True)
        self.dataBrowserTabWidget.setObjectName(_fromUtf8("dataBrowserTabWidget"))
        self.dataBrowserPlusTab = QtGui.QWidget()
        self.dataBrowserPlusTab.setObjectName(_fromUtf8("dataBrowserPlusTab"))
        self.dataBrowserTabWidget.addTab(self.dataBrowserPlusTab, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.dataBrowserTabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.buttonPlotAllData = QtGui.QPushButton(self.tab)
        self.buttonPlotAllData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Plot All Data", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlotAllData.setObjectName(_fromUtf8("buttonPlotAllData"))
        self.horizontalLayout_3.addWidget(self.buttonPlotAllData)
        self.buttonPlotSelectedData = QtGui.QPushButton(self.tab)
        self.buttonPlotSelectedData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Plot Selected Data", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlotSelectedData.setObjectName(_fromUtf8("buttonPlotSelectedData"))
        self.horizontalLayout_3.addWidget(self.buttonPlotSelectedData)
        spacerItem6 = QtGui.QSpacerItem(538, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_19.addLayout(self.verticalLayout_6)
        self.actionTabWidget.addTab(self.tab, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tabSettings)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.tabSettings)
        self.groupBox.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "General Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelComputationBackend = QtGui.QLabel(self.groupBox)
        self.labelComputationBackend.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Select the computation backend BioParkin uses for simulations, sensitivity calculations, etc. (FORTRAN code generation is available here for compatibility and debugging reasons.)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Select the computation backend BioParkin uses for simulations, sensitivity calculations, etc. (FORTRAN code generation is available here for compatibility and debugging reasons.)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setText(QtGui.QApplication.translate("SimulationWorkbench", "Identification Backend:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComputationBackend.setObjectName(_fromUtf8("labelComputationBackend"))
        self.horizontalLayout_2.addWidget(self.labelComputationBackend)
        self.comboBoxBackendSelect = QtGui.QComboBox(self.groupBox)
        self.comboBoxBackendSelect.setObjectName(_fromUtf8("comboBoxBackendSelect"))
        self.comboBoxBackendSelect.addItem(_fromUtf8(""))
        self.comboBoxBackendSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "PARKIN", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBackendSelect.addItem(_fromUtf8(""))
        self.comboBoxBackendSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "NLSCON", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2.addWidget(self.comboBoxBackendSelect)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.checkBoxPlotExpData = QtGui.QCheckBox(self.groupBox)
        self.checkBoxPlotExpData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Include Experimental Data in Simulation Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPlotExpData.setObjectName(_fromUtf8("checkBoxPlotExpData"))
        self.verticalLayout_7.addWidget(self.checkBoxPlotExpData)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBoxTimes = QtGui.QGroupBox(self.tabSettings)
        self.groupBoxTimes.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "Time Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTimes.setObjectName(_fromUtf8("groupBoxTimes"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxTimes)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelStartTime = QtGui.QLabel(self.groupBoxTimes)
        self.labelStartTime.setText(QtGui.QApplication.translate("SimulationWorkbench", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStartTime.setObjectName(_fromUtf8("labelStartTime"))
        self.gridLayout.addWidget(self.labelStartTime, 0, 0, 1, 1)
        self.lineEditStartTime = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditStartTime.setText(_fromUtf8(""))
        self.lineEditStartTime.setObjectName(_fromUtf8("lineEditStartTime"))
        self.gridLayout.addWidget(self.lineEditStartTime, 0, 1, 1, 1)
        self.labelEndTime = QtGui.QLabel(self.groupBoxTimes)
        self.labelEndTime.setText(QtGui.QApplication.translate("SimulationWorkbench", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEndTime.setObjectName(_fromUtf8("labelEndTime"))
        self.gridLayout.addWidget(self.labelEndTime, 1, 0, 1, 1)
        self.lineEditEndTime = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditEndTime.setText(_fromUtf8(""))
        self.lineEditEndTime.setObjectName(_fromUtf8("lineEditEndTime"))
        self.gridLayout.addWidget(self.lineEditEndTime, 1, 1, 1, 1)
        self.labelTimeUnit = QtGui.QLabel(self.groupBoxTimes)
        self.labelTimeUnit.setText(QtGui.QApplication.translate("SimulationWorkbench", "Time Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTimeUnit.setObjectName(_fromUtf8("labelTimeUnit"))
        self.gridLayout.addWidget(self.labelTimeUnit, 2, 0, 1, 1)
        self.lineEditTimeUnit = QtGui.QLineEdit(self.groupBoxTimes)
        self.lineEditTimeUnit.setText(_fromUtf8(""))
        self.lineEditTimeUnit.setObjectName(_fromUtf8("lineEditTimeUnit"))
        self.gridLayout.addWidget(self.lineEditTimeUnit, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBoxTimes)
        self.groupBoxTolerances = QtGui.QGroupBox(self.tabSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTolerances.sizePolicy().hasHeightForWidth())
        self.groupBoxTolerances.setSizePolicy(sizePolicy)
        self.groupBoxTolerances.setTitle(QtGui.QApplication.translate("SimulationWorkbench", "Expert Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTolerances.setFlat(False)
        self.groupBoxTolerances.setCheckable(False)
        self.groupBoxTolerances.setObjectName(_fromUtf8("groupBoxTolerances"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxTolerances)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelRTOL = QtGui.QLabel(self.groupBoxTolerances)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRTOL.sizePolicy().hasHeightForWidth())
        self.labelRTOL.setSizePolicy(sizePolicy)
        self.labelRTOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Relative Tolerance (RTOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRTOL.setObjectName(_fromUtf8("labelRTOL"))
        self.gridLayout_2.addWidget(self.labelRTOL, 0, 0, 1, 1)
        self.lineEditRTOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditRTOL.setText(_fromUtf8(""))
        self.lineEditRTOL.setObjectName(_fromUtf8("lineEditRTOL"))
        self.gridLayout_2.addWidget(self.lineEditRTOL, 0, 1, 1, 1)
        self.labelATOL = QtGui.QLabel(self.groupBoxTolerances)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelATOL.sizePolicy().hasHeightForWidth())
        self.labelATOL.setSizePolicy(sizePolicy)
        self.labelATOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Absolute tolerance used by the integrator", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Absolute Tolerance (ATOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelATOL.setObjectName(_fromUtf8("labelATOL"))
        self.gridLayout_2.addWidget(self.labelATOL, 1, 0, 1, 1)
        self.lineEditATOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditATOL.setText(_fromUtf8(""))
        self.lineEditATOL.setObjectName(_fromUtf8("lineEditATOL"))
        self.gridLayout_2.addWidget(self.lineEditATOL, 1, 1, 1, 1)
        self.labelXTOL = QtGui.QLabel(self.groupBoxTolerances)
        self.labelXTOL.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setStatusTip(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setWhatsThis(QtGui.QApplication.translate("SimulationWorkbench", "Required tolerance for Gauß Newton", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Required Tolerance (XTOL)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXTOL.setObjectName(_fromUtf8("labelXTOL"))
        self.gridLayout_2.addWidget(self.labelXTOL, 2, 0, 1, 1)
        self.lineEditXTOL = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditXTOL.setObjectName(_fromUtf8("lineEditXTOL"))
        self.gridLayout_2.addWidget(self.lineEditXTOL, 2, 1, 1, 1)
        self.labelJACGEN = QtGui.QLabel(self.groupBoxTolerances)
        self.labelJACGEN.setText(QtGui.QApplication.translate("SimulationWorkbench", "Jacobian", None, QtGui.QApplication.UnicodeUTF8))
        self.labelJACGEN.setObjectName(_fromUtf8("labelJACGEN"))
        self.gridLayout_2.addWidget(self.labelJACGEN, 5, 0, 1, 1)
        self.labelNONLIN = QtGui.QLabel(self.groupBoxTolerances)
        self.labelNONLIN.setText(QtGui.QApplication.translate("SimulationWorkbench", "Problem Type", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNONLIN.setObjectName(_fromUtf8("labelNONLIN"))
        self.gridLayout_2.addWidget(self.labelNONLIN, 6, 0, 1, 1)
        self.comboBoxProblemTypeSelect = QtGui.QComboBox(self.groupBoxTolerances)
        self.comboBoxProblemTypeSelect.setObjectName(_fromUtf8("comboBoxProblemTypeSelect"))
        self.comboBoxProblemTypeSelect.addItem(_fromUtf8(""))
        self.comboBoxProblemTypeSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxProblemTypeSelect.addItem(_fromUtf8(""))
        self.comboBoxProblemTypeSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "mildly nonlinear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxProblemTypeSelect.addItem(_fromUtf8(""))
        self.comboBoxProblemTypeSelect.setItemText(2, QtGui.QApplication.translate("SimulationWorkbench", "highly nonlinear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxProblemTypeSelect.addItem(_fromUtf8(""))
        self.comboBoxProblemTypeSelect.setItemText(3, QtGui.QApplication.translate("SimulationWorkbench", "extremely nonlinear", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_2.addWidget(self.comboBoxProblemTypeSelect, 6, 1, 1, 1)
        self.labelRSCAL = QtGui.QLabel(self.groupBoxTolerances)
        self.labelRSCAL.setText(QtGui.QApplication.translate("SimulationWorkbench", "Residual Scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRSCAL.setObjectName(_fromUtf8("labelRSCAL"))
        self.gridLayout_2.addWidget(self.labelRSCAL, 7, 0, 1, 1)
        self.comboBoxResidualScalingSelect = QtGui.QComboBox(self.groupBoxTolerances)
        self.comboBoxResidualScalingSelect.setObjectName(_fromUtf8("comboBoxResidualScalingSelect"))
        self.comboBoxResidualScalingSelect.addItem(_fromUtf8(""))
        self.comboBoxResidualScalingSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "no extra scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResidualScalingSelect.addItem(_fromUtf8(""))
        self.comboBoxResidualScalingSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "relative scaling (w.r.t. upper/lower machine bound)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxResidualScalingSelect.addItem(_fromUtf8(""))
        self.comboBoxResidualScalingSelect.setItemText(2, QtGui.QApplication.translate("SimulationWorkbench", "absolute scaling (w.r.t. upper/lower machine bound)", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_2.addWidget(self.comboBoxResidualScalingSelect, 7, 1, 1, 1)
        self.labelLPOS = QtGui.QLabel(self.groupBoxTolerances)
        self.labelLPOS.setText(QtGui.QApplication.translate("SimulationWorkbench", "Parameter Constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLPOS.setObjectName(_fromUtf8("labelLPOS"))
        self.gridLayout_2.addWidget(self.labelLPOS, 8, 0, 1, 1)
        self.comboBoxParameterConstraintsSelect = QtGui.QComboBox(self.groupBoxTolerances)
        self.comboBoxParameterConstraintsSelect.setObjectName(_fromUtf8("comboBoxParameterConstraintsSelect"))
        self.comboBoxParameterConstraintsSelect.addItem(_fromUtf8(""))
        self.comboBoxParameterConstraintsSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "no constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxParameterConstraintsSelect.addItem(_fromUtf8(""))
        self.comboBoxParameterConstraintsSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "strictly positive (exponential transformation)", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_2.addWidget(self.comboBoxParameterConstraintsSelect, 8, 1, 1, 1)
        self.checkBoxNoAutoRowScale = QtGui.QCheckBox(self.groupBoxTolerances)
        self.checkBoxNoAutoRowScale.setText(QtGui.QApplication.translate("SimulationWorkbench", "No Automatic Row Scaling of Jacobian", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNoAutoRowScale.setObjectName(_fromUtf8("checkBoxNoAutoRowScale"))
        self.gridLayout_2.addWidget(self.checkBoxNoAutoRowScale, 4, 1, 1, 1)
        self.comboBoxJacobianSelect = QtGui.QComboBox(self.groupBoxTolerances)
        self.comboBoxJacobianSelect.setObjectName(_fromUtf8("comboBoxJacobianSelect"))
        self.comboBoxJacobianSelect.addItem(_fromUtf8(""))
        self.comboBoxJacobianSelect.setItemText(0, QtGui.QApplication.translate("SimulationWorkbench", "Variational Equations", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxJacobianSelect.addItem(_fromUtf8(""))
        self.comboBoxJacobianSelect.setItemText(1, QtGui.QApplication.translate("SimulationWorkbench", "Numerical Differentiation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxJacobianSelect.addItem(_fromUtf8(""))
        self.comboBoxJacobianSelect.setItemText(2, QtGui.QApplication.translate("SimulationWorkbench", "Numerical Diff. with Feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_2.addWidget(self.comboBoxJacobianSelect, 5, 1, 1, 1)
        self.lineEditMaxNumNewtonSteps = QtGui.QLineEdit(self.groupBoxTolerances)
        self.lineEditMaxNumNewtonSteps.setText(_fromUtf8(""))
        self.lineEditMaxNumNewtonSteps.setObjectName(_fromUtf8("lineEditMaxNumNewtonSteps"))
        self.gridLayout_2.addWidget(self.lineEditMaxNumNewtonSteps, 3, 1, 1, 1)
        self.labelMaxNumNewtonSteps = QtGui.QLabel(self.groupBoxTolerances)
        self.labelMaxNumNewtonSteps.setText(QtGui.QApplication.translate("SimulationWorkbench", "Max. # Newton Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMaxNumNewtonSteps.setObjectName(_fromUtf8("labelMaxNumNewtonSteps"))
        self.gridLayout_2.addWidget(self.labelMaxNumNewtonSteps, 3, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBoxTolerances)
        spacerItem8 = QtGui.QSpacerItem(20, 238, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.simulateButtonSettings = QtGui.QPushButton(self.tabSettings)
        self.simulateButtonSettings.setText(QtGui.QApplication.translate("SimulationWorkbench", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButtonSettings.setObjectName(_fromUtf8("simulateButtonSettings"))
        self.verticalLayout_4.addWidget(self.simulateButtonSettings)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.actionTabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.actionTabWidget)
        self.actionSimulate = QtGui.QAction(SimulationWorkbench)
        self.actionSimulate.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Simulate with current settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulate.setObjectName(_fromUtf8("actionSimulate"))
        self.actionReset = QtGui.QAction(SimulationWorkbench)
        self.actionReset.setText(QtGui.QApplication.translate("SimulationWorkbench", "&Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionComputeSensitivityOverview = QtGui.QAction(SimulationWorkbench)
        self.actionComputeSensitivityOverview.setText(QtGui.QApplication.translate("SimulationWorkbench", "Compute Sensitivity Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivityOverview.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Compute the sensitivitiy overview (sensitivity trajectories) of the currently selected Species", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivityOverview.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComputeSensitivityOverview.setObjectName(_fromUtf8("actionComputeSensitivityOverview"))
        self.actionResetSpecies = QtGui.QAction(SimulationWorkbench)
        self.actionResetSpecies.setText(QtGui.QApplication.translate("SimulationWorkbench", "Reset Species", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetSpecies.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Resets all Species values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetSpecies.setObjectName(_fromUtf8("actionResetSpecies"))
        self.actionResetParameters = QtGui.QAction(SimulationWorkbench)
        self.actionResetParameters.setText(QtGui.QApplication.translate("SimulationWorkbench", "Reset Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetParameters.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Resets all Parameter values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResetParameters.setObjectName(_fromUtf8("actionResetParameters"))
        self.actionEstimateParameterValues = QtGui.QAction(SimulationWorkbench)
        self.actionEstimateParameterValues.setText(QtGui.QApplication.translate("SimulationWorkbench", "Estimate Parameter Values", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEstimateParameterValues.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Starts the parameter value estimation process", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEstimateParameterValues.setObjectName(_fromUtf8("actionEstimateParameterValues"))
        self.actionPerturbExperimentalData = QtGui.QAction(SimulationWorkbench)
        self.actionPerturbExperimentalData.setText(QtGui.QApplication.translate("SimulationWorkbench", "Perturb Experimental Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPerturbExperimentalData.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Perturbs the loaded experimental data by the given percentage.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPerturbExperimentalData.setObjectName(_fromUtf8("actionPerturbExperimentalData"))
        self.actionSelectAllParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionSelectAllParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAllParametersForSensitivity.setObjectName(_fromUtf8("actionSelectAllParametersForSensitivity"))
        self.actionDeselectAllParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionDeselectAllParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselectAllParametersForSensitivity.setObjectName(_fromUtf8("actionDeselectAllParametersForSensitivity"))
        self.actionInvertSelectionOfParametersForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionInvertSelectionOfParametersForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection of Parameters for Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvertSelectionOfParametersForSensitivity.setObjectName(_fromUtf8("actionInvertSelectionOfParametersForSensitivity"))
        self.actionSelect_All_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionSelect_All_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select All Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All_Parameters_for_Estimation.setObjectName(_fromUtf8("actionSelect_All_Parameters_for_Estimation"))
        self.actionDeselect_All_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionDeselect_All_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect All Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselect_All_Parameters_for_Estimation.setObjectName(_fromUtf8("actionDeselect_All_Parameters_for_Estimation"))
        self.actionInvert_Selection_of_Parameters_for_Estimation = QtGui.QAction(SimulationWorkbench)
        self.actionInvert_Selection_of_Parameters_for_Estimation.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert Selection of Parameters for Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert_Selection_of_Parameters_for_Estimation.setObjectName(_fromUtf8("actionInvert_Selection_of_Parameters_for_Estimation"))
        self.actionNew_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionNew_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "New Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Create a new Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Parameter_Set.setObjectName(_fromUtf8("actionNew_Parameter_Set"))
        self.actionDuplicate_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionDuplicate_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "Duplicate Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Create a new Parameter Set by duplicating the selected one", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate_Parameter_Set.setObjectName(_fromUtf8("actionDuplicate_Parameter_Set"))
        self.actionRemove_Parameter_Set = QtGui.QAction(SimulationWorkbench)
        self.actionRemove_Parameter_Set.setText(QtGui.QApplication.translate("SimulationWorkbench", "Remove Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Parameter_Set.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Remove selected Parameter Set", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Parameter_Set.setObjectName(_fromUtf8("actionRemove_Parameter_Set"))
        self.actionCompute_Detailed_Sensitivities = QtGui.QAction(SimulationWorkbench)
        self.actionCompute_Detailed_Sensitivities.setText(QtGui.QApplication.translate("SimulationWorkbench", "Compute Detailed Sensitivities", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompute_Detailed_Sensitivities.setToolTip(QtGui.QApplication.translate("SimulationWorkbench", "Compute the sensitivities of the selected parameters at given timepoints.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompute_Detailed_Sensitivities.setShortcut(QtGui.QApplication.translate("SimulationWorkbench", "Ctrl+3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompute_Detailed_Sensitivities.setObjectName(_fromUtf8("actionCompute_Detailed_Sensitivities"))
        self.actionSelectAllSpeciesForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionSelectAllSpeciesForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Select all Species for Sensitivity Computation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAllSpeciesForSensitivity.setObjectName(_fromUtf8("actionSelectAllSpeciesForSensitivity"))
        self.actionDeselectAllSpeciesForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionDeselectAllSpeciesForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Deselect all Species for Sensitivity Calculation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeselectAllSpeciesForSensitivity.setObjectName(_fromUtf8("actionDeselectAllSpeciesForSensitivity"))
        self.actionInvertSelectionOfSpeciesForSensitivity = QtGui.QAction(SimulationWorkbench)
        self.actionInvertSelectionOfSpeciesForSensitivity.setText(QtGui.QApplication.translate("SimulationWorkbench", "Invert the selection of Species for Sensitivity Calculation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvertSelectionOfSpeciesForSensitivity.setObjectName(_fromUtf8("actionInvertSelectionOfSpeciesForSensitivity"))

        self.retranslateUi(SimulationWorkbench)
        self.actionTabWidget.setCurrentIndex(0)
        self.dataBrowserTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.simulateButtonSpecies, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.computeSensitivityOverviewButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionComputeSensitivityOverview.trigger)
        QtCore.QObject.connect(self.simulateButtonParams, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.estimateParamsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionEstimateParameterValues.trigger)
        QtCore.QObject.connect(self.simulateButtonSettings, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSimulate.trigger)
        QtCore.QObject.connect(self.buttonDeselectAllSensitivity, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionDeselectAllParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonInvertSelectionSensitivity, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionInvertSelectionOfParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonSelectAllSensitivity, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSelectAllParametersForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonDeselectAllParamEst, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionDeselect_All_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonInvertSelectionParamEst, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionInvert_Selection_of_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonSelectAllParamEst, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSelect_All_Parameters_for_Estimation.trigger)
        QtCore.QObject.connect(self.buttonParamSetDuplicate, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionDuplicate_Parameter_Set.trigger)
        QtCore.QObject.connect(self.buttonParamSetNew, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionNew_Parameter_Set.trigger)
        QtCore.QObject.connect(self.buttonParamSetRemove, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionRemove_Parameter_Set.trigger)
        QtCore.QObject.connect(self.computeDetailedSensitivitiesButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionCompute_Detailed_Sensitivities.trigger)
        QtCore.QObject.connect(self.buttonDeselectAllSensitivitySpecies, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionDeselectAllSpeciesForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonInvertSelectionSensitivitySpecies, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionInvertSelectionOfSpeciesForSensitivity.trigger)
        QtCore.QObject.connect(self.buttonSelectAllSensitivitySpecies, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSelectAllSpeciesForSensitivity.trigger)
        QtCore.QMetaObject.connectSlotsByName(SimulationWorkbench)

    def retranslateUi(self, SimulationWorkbench):
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSpecies), QtGui.QApplication.translate("SimulationWorkbench", "&Species", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabParameters), QtGui.QApplication.translate("SimulationWorkbench", "&Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabParameterSets), QtGui.QApplication.translate("SimulationWorkbench", "Parameter Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSensitivity), QtGui.QApplication.translate("SimulationWorkbench", "&Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabFit), QtGui.QApplication.translate("SimulationWorkbench", "&Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBrowserTabWidget.setTabText(self.dataBrowserTabWidget.indexOf(self.dataBrowserPlusTab), QtGui.QApplication.translate("SimulationWorkbench", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tab), QtGui.QApplication.translate("SimulationWorkbench", "Data Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabWidget.setTabText(self.actionTabWidget.indexOf(self.tabSettings), QtGui.QApplication.translate("SimulationWorkbench", "&Settings", None, QtGui.QApplication.UnicodeUTF8))

